// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --version 6
// RUN: %clang_cc1 -triple giselle -O0 -emit-llvm %s -o - | FileCheck %s --check-prefix=O0
// RUN: %clang_cc1 -triple giselle -O1 -emit-llvm %s -o - | FileCheck %s --check-prefix=O1
// REQUIRES: giselle-registered-target

// How to run: python3 llvm/utils/update_cc_test_checks.py --clang build/bin/clang clang/test/CodeGen/Giselle/test-suite.c

// Check that the Giselle target is properly hooked up for the target agnostic
// optimizers.

// O0-LABEL: define dso_local i32 @main(
// O0-SAME: ) #[[ATTR0:[0-9]+]] {
// O0-NEXT:  [[ENTRY:.*:]]
// O0-NEXT:    [[RETVAL:%.*]] = alloca i32, align 4
// O0-NEXT:    store i32 0, ptr [[RETVAL]], align 4
// O0-NEXT:    ret i32 0
//
// O1-LABEL: define dso_local noundef i32 @main(
// O1-SAME: ) local_unnamed_addr #[[ATTR0:[0-9]+]] {
// O1-NEXT:  [[ENTRY:.*:]]
// O1-NEXT:    ret i32 0
//
int main()
{
  return 0;
}

// O0-LABEL: define dso_local i32 @f0(
// O0-SAME: ) #[[ATTR0]] {
// O0-NEXT:  [[ENTRY:.*:]]
// O0-NEXT:    ret i32 0
//
// O1-LABEL: define dso_local noundef i32 @f0(
// O1-SAME: ) local_unnamed_addr #[[ATTR0]] {
// O1-NEXT:  [[ENTRY:.*:]]
// O1-NEXT:    ret i32 0
//
int f0 ()
{
  return 3-3;
}

// O0-LABEL: define dso_local i32 @f1(
// O0-SAME: ) #[[ATTR0]] {
// O0-NEXT:  [[ENTRY:.*:]]
// O0-NEXT:    [[X:%.*]] = alloca i32, align 4
// O0-NEXT:    store i32 4, ptr [[X]], align 4
// O0-NEXT:    [[TMP0:%.*]] = load i32, ptr [[X]], align 4
// O0-NEXT:    [[SUB:%.*]] = sub nsw i32 [[TMP0]], 4
// O0-NEXT:    ret i32 [[SUB]]
//
// O1-LABEL: define dso_local noundef i32 @f1(
// O1-SAME: ) local_unnamed_addr #[[ATTR0]] {
// O1-NEXT:  [[ENTRY:.*:]]
// O1-NEXT:    ret i32 0
//
int f1()
{
  int x;

  x = 4;
  return x - 4;
}

// O0-LABEL: define dso_local i32 @f2(
// O0-SAME: ) #[[ATTR0]] {
// O0-NEXT:  [[ENTRY:.*:]]
// O0-NEXT:    [[X:%.*]] = alloca i32, align 4
// O0-NEXT:    [[P:%.*]] = alloca ptr, align 4
// O0-NEXT:    store i32 4, ptr [[X]], align 4
// O0-NEXT:    store ptr [[X]], ptr [[P]], align 4
// O0-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P]], align 4
// O0-NEXT:    store i32 0, ptr [[TMP0]], align 4
// O0-NEXT:    [[TMP1:%.*]] = load ptr, ptr [[P]], align 4
// O0-NEXT:    [[TMP2:%.*]] = load i32, ptr [[TMP1]], align 4
// O0-NEXT:    ret i32 [[TMP2]]
//
// O1-LABEL: define dso_local noundef i32 @f2(
// O1-SAME: ) local_unnamed_addr #[[ATTR0]] {
// O1-NEXT:  [[ENTRY:.*:]]
// O1-NEXT:    ret i32 0
//
int f2()
{
  int x;
  int *p;

  x = 4;
  p = &x;
  *p = 0;

  return *p;
}

// O0-LABEL: define dso_local i32 @f3(
// O0-SAME: ) #[[ATTR0]] {
// O0-NEXT:  [[ENTRY:.*:]]
// O0-NEXT:    [[RETVAL:%.*]] = alloca i32, align 4
// O0-NEXT:    [[X:%.*]] = alloca i32, align 4
// O0-NEXT:    [[P:%.*]] = alloca ptr, align 4
// O0-NEXT:    [[PP:%.*]] = alloca ptr, align 4
// O0-NEXT:    store i32 0, ptr [[X]], align 4
// O0-NEXT:    store ptr [[X]], ptr [[P]], align 4
// O0-NEXT:    store ptr [[P]], ptr [[PP]], align 4
// O0-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P]], align 4
// O0-NEXT:    [[TMP1:%.*]] = load i32, ptr [[TMP0]], align 4
// O0-NEXT:    [[TOBOOL:%.*]] = icmp ne i32 [[TMP1]], 0
// O0-NEXT:    br i1 [[TOBOOL]], label %[[IF_THEN:.*]], label %[[IF_END:.*]]
// O0:       [[IF_THEN]]:
// O0-NEXT:    store i32 1, ptr [[RETVAL]], align 4
// O0-NEXT:    br label %[[RETURN:.*]]
// O0:       [[IF_END]]:
// O0-NEXT:    [[TMP2:%.*]] = load ptr, ptr [[PP]], align 4
// O0-NEXT:    [[TMP3:%.*]] = load ptr, ptr [[TMP2]], align 4
// O0-NEXT:    [[TMP4:%.*]] = load i32, ptr [[TMP3]], align 4
// O0-NEXT:    [[TOBOOL1:%.*]] = icmp ne i32 [[TMP4]], 0
// O0-NEXT:    br i1 [[TOBOOL1]], label %[[IF_THEN2:.*]], label %[[IF_ELSE:.*]]
// O0:       [[IF_THEN2]]:
// O0-NEXT:    store i32 1, ptr [[RETVAL]], align 4
// O0-NEXT:    br label %[[RETURN]]
// O0:       [[IF_ELSE]]:
// O0-NEXT:    [[TMP5:%.*]] = load ptr, ptr [[PP]], align 4
// O0-NEXT:    [[TMP6:%.*]] = load ptr, ptr [[TMP5]], align 4
// O0-NEXT:    store i32 1, ptr [[TMP6]], align 4
// O0-NEXT:    br label %[[IF_END3:.*]]
// O0:       [[IF_END3]]:
// O0-NEXT:    [[TMP7:%.*]] = load i32, ptr [[X]], align 4
// O0-NEXT:    [[TOBOOL4:%.*]] = icmp ne i32 [[TMP7]], 0
// O0-NEXT:    br i1 [[TOBOOL4]], label %[[IF_THEN5:.*]], label %[[IF_ELSE6:.*]]
// O0:       [[IF_THEN5]]:
// O0-NEXT:    store i32 0, ptr [[RETVAL]], align 4
// O0-NEXT:    br label %[[RETURN]]
// O0:       [[IF_ELSE6]]:
// O0-NEXT:    store i32 1, ptr [[RETVAL]], align 4
// O0-NEXT:    br label %[[RETURN]]
// O0:       [[RETURN]]:
// O0-NEXT:    [[TMP8:%.*]] = load i32, ptr [[RETVAL]], align 4
// O0-NEXT:    ret i32 [[TMP8]]
//
// O1-LABEL: define dso_local noundef i32 @f3(
// O1-SAME: ) local_unnamed_addr #[[ATTR0]] {
// O1-NEXT:  [[ENTRY:.*:]]
// O1-NEXT:    ret i32 0
//
int f3()
{
  int x;
  int *p;
  int **pp;

  x = 0;
  p = &x;
  pp = &p;

  if(*p)
    return 1;
  if(**pp)
    return 1;
  else
    **pp = 1;

  if(x)
    return 0;
  else
    return 1;
}

// O0-LABEL: define dso_local i32 @f4(
// O0-SAME: ) #[[ATTR0]] {
// O0-NEXT:  [[ENTRY:.*:]]
// O0-NEXT:    [[X:%.*]] = alloca i32, align 4
// O0-NEXT:    store i32 50, ptr [[X]], align 4
// O0-NEXT:    br label %[[WHILE_COND:.*]]
// O0:       [[WHILE_COND]]:
// O0-NEXT:    [[TMP0:%.*]] = load i32, ptr [[X]], align 4
// O0-NEXT:    [[TOBOOL:%.*]] = icmp ne i32 [[TMP0]], 0
// O0-NEXT:    br i1 [[TOBOOL]], label %[[WHILE_BODY:.*]], label %[[WHILE_END:.*]]
// O0:       [[WHILE_BODY]]:
// O0-NEXT:    [[TMP1:%.*]] = load i32, ptr [[X]], align 4
// O0-NEXT:    [[SUB:%.*]] = sub nsw i32 [[TMP1]], 1
// O0-NEXT:    store i32 [[SUB]], ptr [[X]], align 4
// O0-NEXT:    br label %[[WHILE_COND]], !llvm.loop [[LOOP2:![0-9]+]]
// O0:       [[WHILE_END]]:
// O0-NEXT:    [[TMP2:%.*]] = load i32, ptr [[X]], align 4
// O0-NEXT:    ret i32 [[TMP2]]
//
// O1-LABEL: define dso_local noundef i32 @f4(
// O1-SAME: ) local_unnamed_addr #[[ATTR0]] {
// O1-NEXT:  [[ENTRY:.*:]]
// O1-NEXT:    ret i32 0
//
int f4()
{
  int x;

  x = 50;
  while (x)
    x = x - 1;
  return x;
}

// O0-LABEL: define dso_local i32 @f5(
// O0-SAME: ) #[[ATTR0]] {
// O0-NEXT:  [[ENTRY:.*:]]
// O0-NEXT:    [[RETVAL:%.*]] = alloca i32, align 4
// O0-NEXT:    [[X:%.*]] = alloca i32, align 4
// O0-NEXT:    store i32 1, ptr [[X]], align 4
// O0-NEXT:    store i32 10, ptr [[X]], align 4
// O0-NEXT:    br label %[[FOR_COND:.*]]
// O0:       [[FOR_COND]]:
// O0-NEXT:    [[TMP0:%.*]] = load i32, ptr [[X]], align 4
// O0-NEXT:    [[TOBOOL:%.*]] = icmp ne i32 [[TMP0]], 0
// O0-NEXT:    br i1 [[TOBOOL]], label %[[FOR_BODY:.*]], label %[[FOR_END:.*]]
// O0:       [[FOR_BODY]]:
// O0-NEXT:    br label %[[FOR_INC:.*]]
// O0:       [[FOR_INC]]:
// O0-NEXT:    [[TMP1:%.*]] = load i32, ptr [[X]], align 4
// O0-NEXT:    [[SUB:%.*]] = sub nsw i32 [[TMP1]], 1
// O0-NEXT:    store i32 [[SUB]], ptr [[X]], align 4
// O0-NEXT:    br label %[[FOR_COND]], !llvm.loop [[LOOP4:![0-9]+]]
// O0:       [[FOR_END]]:
// O0-NEXT:    [[TMP2:%.*]] = load i32, ptr [[X]], align 4
// O0-NEXT:    [[TOBOOL1:%.*]] = icmp ne i32 [[TMP2]], 0
// O0-NEXT:    br i1 [[TOBOOL1]], label %[[IF_THEN:.*]], label %[[IF_END:.*]]
// O0:       [[IF_THEN]]:
// O0-NEXT:    store i32 1, ptr [[RETVAL]], align 4
// O0-NEXT:    br label %[[RETURN:.*]]
// O0:       [[IF_END]]:
// O0-NEXT:    store i32 10, ptr [[X]], align 4
// O0-NEXT:    br label %[[FOR_COND2:.*]]
// O0:       [[FOR_COND2]]:
// O0-NEXT:    [[TMP3:%.*]] = load i32, ptr [[X]], align 4
// O0-NEXT:    [[TOBOOL3:%.*]] = icmp ne i32 [[TMP3]], 0
// O0-NEXT:    br i1 [[TOBOOL3]], label %[[FOR_BODY4:.*]], label %[[FOR_END6:.*]]
// O0:       [[FOR_BODY4]]:
// O0-NEXT:    [[TMP4:%.*]] = load i32, ptr [[X]], align 4
// O0-NEXT:    [[SUB5:%.*]] = sub nsw i32 [[TMP4]], 1
// O0-NEXT:    store i32 [[SUB5]], ptr [[X]], align 4
// O0-NEXT:    br label %[[FOR_COND2]], !llvm.loop [[LOOP5:![0-9]+]]
// O0:       [[FOR_END6]]:
// O0-NEXT:    [[TMP5:%.*]] = load i32, ptr [[X]], align 4
// O0-NEXT:    store i32 [[TMP5]], ptr [[RETVAL]], align 4
// O0-NEXT:    br label %[[RETURN]]
// O0:       [[RETURN]]:
// O0-NEXT:    [[TMP6:%.*]] = load i32, ptr [[RETVAL]], align 4
// O0-NEXT:    ret i32 [[TMP6]]
//
// O1-LABEL: define dso_local noundef i32 @f5(
// O1-SAME: ) local_unnamed_addr #[[ATTR0]] {
// O1-NEXT:  [[ENTRY:.*:]]
// O1-NEXT:    ret i32 0
//
int f5()
{
  int x;

  x = 1;
  for(x = 10; x; x = x - 1)
    ;
  if(x)
    return 1;
  x = 10;
  for (;x;)
    x = x - 1;
  return x;
}

// O0-LABEL: define dso_local i32 @f6(
// O0-SAME: ) #[[ATTR0]] {
// O0-NEXT:  [[ENTRY:.*:]]
// O0-NEXT:    [[X:%.*]] = alloca i32, align 4
// O0-NEXT:    store i32 50, ptr [[X]], align 4
// O0-NEXT:    br label %[[DO_BODY:.*]]
// O0:       [[DO_BODY]]:
// O0-NEXT:    [[TMP0:%.*]] = load i32, ptr [[X]], align 4
// O0-NEXT:    [[SUB:%.*]] = sub nsw i32 [[TMP0]], 1
// O0-NEXT:    store i32 [[SUB]], ptr [[X]], align 4
// O0-NEXT:    br label %[[DO_COND:.*]]
// O0:       [[DO_COND]]:
// O0-NEXT:    [[TMP1:%.*]] = load i32, ptr [[X]], align 4
// O0-NEXT:    [[TOBOOL:%.*]] = icmp ne i32 [[TMP1]], 0
// O0-NEXT:    br i1 [[TOBOOL]], label %[[DO_BODY]], label %[[DO_END:.*]], !llvm.loop [[LOOP6:![0-9]+]]
// O0:       [[DO_END]]:
// O0-NEXT:    [[TMP2:%.*]] = load i32, ptr [[X]], align 4
// O0-NEXT:    ret i32 [[TMP2]]
//
// O1-LABEL: define dso_local noundef i32 @f6(
// O1-SAME: ) local_unnamed_addr #[[ATTR0]] {
// O1-NEXT:  [[ENTRY:.*:]]
// O1-NEXT:    ret i32 0
//
int f6()
{
	int x;

	x = 50;
	do
		x = x - 1;
	while(x);
	return x;
}

// O0-LABEL: define dso_local i32 @f7(
// O0-SAME: ) #[[ATTR0]] {
// O0-NEXT:  [[ENTRY:.*:]]
// O0-NEXT:    [[X:%.*]] = alloca i32, align 4
// O0-NEXT:    store i32 1, ptr [[X]], align 4
// O0-NEXT:    [[TMP0:%.*]] = load i32, ptr [[X]], align 4
// O0-NEXT:    [[MUL:%.*]] = mul nsw i32 [[TMP0]], 10
// O0-NEXT:    store i32 [[MUL]], ptr [[X]], align 4
// O0-NEXT:    [[TMP1:%.*]] = load i32, ptr [[X]], align 4
// O0-NEXT:    [[DIV:%.*]] = sdiv i32 [[TMP1]], 2
// O0-NEXT:    store i32 [[DIV]], ptr [[X]], align 4
// O0-NEXT:    [[TMP2:%.*]] = load i32, ptr [[X]], align 4
// O0-NEXT:    [[REM:%.*]] = srem i32 [[TMP2]], 3
// O0-NEXT:    store i32 [[REM]], ptr [[X]], align 4
// O0-NEXT:    [[TMP3:%.*]] = load i32, ptr [[X]], align 4
// O0-NEXT:    [[SUB:%.*]] = sub nsw i32 [[TMP3]], 2
// O0-NEXT:    ret i32 [[SUB]]
//
// O1-LABEL: define dso_local noundef i32 @f7(
// O1-SAME: ) local_unnamed_addr #[[ATTR0]] {
// O1-NEXT:  [[ENTRY:.*:]]
// O1-NEXT:    ret i32 0
//
int f7()
{
	int x;

	x = 1;
	x = x * 10;
	x = x / 2;
	x = x % 3;
	return x - 2;
}

// O0-LABEL: define dso_local i32 @f8(
// O0-SAME: ) #[[ATTR0]] {
// O0-NEXT:  [[ENTRY:.*:]]
// O0-NEXT:    br label %[[START:.*]]
// O0:       [[START]]:
// O0-NEXT:    br label %[[NEXT:.*]]
// O0:       [[SUCCESS:.*]]:
// O0-NEXT:    ret i32 0
// O0:       [[NEXT]]:
// O0-NEXT:    br label %[[FOO:.*]]
// O0:       [[FOO]]:
// O0-NEXT:    br label %[[SUCCESS]]
//
// O1-LABEL: define dso_local noundef i32 @f8(
// O1-SAME: ) local_unnamed_addr #[[ATTR0]] {
// O1-NEXT:  [[ENTRY:.*:]]
// O1-NEXT:    ret i32 0
//
int f8()
{
	start:
		goto next;
		return 1;
	success:
		return 0;
	next:
	foo:
		goto success;
		return 1;
}

// O0-LABEL: define dso_local i32 @f9(
// O0-SAME: ) #[[ATTR0]] {
// O0-NEXT:  [[ENTRY:.*:]]
// O0-NEXT:    [[X:%.*]] = alloca i32, align 4
// O0-NEXT:    [[Y:%.*]] = alloca i32, align 4
// O0-NEXT:    store i32 0, ptr [[Y]], align 4
// O0-NEXT:    store i32 0, ptr [[X]], align 4
// O0-NEXT:    [[TMP0:%.*]] = load i32, ptr [[X]], align 4
// O0-NEXT:    ret i32 [[TMP0]]
//
// O1-LABEL: define dso_local noundef i32 @f9(
// O1-SAME: ) local_unnamed_addr #[[ATTR0]] {
// O1-NEXT:  [[ENTRY:.*:]]
// O1-NEXT:    ret i32 0
//
int f9()
{
	int x;
	int y;
	x = y = 0;
	return x;
}

// O0-LABEL: define dso_local i32 @f10(
// O0-SAME: ) #[[ATTR0]] {
// O0-NEXT:  [[ENTRY:.*:]]
// O0-NEXT:    ret i32 0
//
// O1-LABEL: define dso_local noundef i32 @f10(
// O1-SAME: ) local_unnamed_addr #[[ATTR0]] {
// O1-NEXT:  [[ENTRY:.*:]]
// O1-NEXT:    ret i32 0
//
int f10()
{
	return (2 + 2) * 2 - 8;
}

//.
// O0: [[LOOP2]] = distinct !{[[LOOP2]], [[META3:![0-9]+]]}
// O0: [[META3]] = !{!"llvm.loop.mustprogress"}
// O0: [[LOOP4]] = distinct !{[[LOOP4]], [[META3]]}
// O0: [[LOOP5]] = distinct !{[[LOOP5]], [[META3]]}
// O0: [[LOOP6]] = distinct !{[[LOOP6]], [[META3]]}
//.
