; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; Example how to run: python3 llvm/utils/update_llc_test_checks.py --llc-binary build/bin/llc llvm/test/CodeGen/Giselle/e2e-abi.ll

; RUN: llc -mtriple giselle-- -o - %s -global-isel=1 -global-isel-abort=1 -verify-machineinstrs | FileCheck %s

target triple="giselle--"

define void @empty() {
; CHECK-LABEL: empty:
; CHECK:       # %bb.0:
; CHECK-NEXT:    jalr x0, 0(x1)
  ret void
}
