# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 5
# How to run: python3 llvm/utils/update_mir_test_checks.py --llc-binary build/bin/llc llvm/test/CodeGen/Giselle/instr-select-sltu.mir

# RUN: llc %s -global-isel -global-isel-abort=1 -run-pass=instruction-select -o - -mtriple giselle -verify-machineinstrs | FileCheck %s
---
name: selectSltu
legalized: true
regBankSelected: true
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $x10, $x11

    ; CHECK-LABEL: name: selectSltu
    ; CHECK: liveins: $x10, $x11, $x1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:gpr32 = COPY $x1
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:gpr32 = COPY $x10
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:gpr32 = COPY $x11
    ; CHECK-NEXT: [[SLTU:%[0-9]+]]:gpr32 = SLTU [[COPY1]], [[COPY2]]
    ; CHECK-NEXT: $x10 = COPY [[SLTU]]
    ; CHECK-NEXT: $x1 = COPY [[COPY]]
    ; CHECK-NEXT: RET_PSEUDO implicit $x10
    %0:gprb(s32) = COPY $x10
    %1:gprb(s32) = COPY $x11
    %2:gprb(s32) = G_ICMP intpred(ult), %0, %1
    $x10 = COPY %2
    RET_PSEUDO implicit $x10
...
