; NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 6
; Example how to run: python3 llvm/utils/update_mir_test_checks.py --llc-binary build/bin/llc llvm/test/CodeGen/Giselle/ir-translator.ll

; RUN: llc -o - %s -global-isel -global-isel-abort=1 --stop-after=irtranslator | FileCheck %s
target triple="giselle--"

define void @empty() {
  ; CHECK-LABEL: name: empty
  ; CHECK: bb.1 (%ir-block.0):
  ; CHECK-NEXT:   $x0 = RET_PSEUDO $x1, 0, implicit $x1
  ret void
}

define i32 @oneArgi32(i32 %arg) {
  ; CHECK-LABEL: name: oneArgi32
  ; CHECK: bb.1 (%ir-block.0):
  ; CHECK-NEXT:   liveins: $x10
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:_(s32) = COPY $x10
  ; CHECK-NEXT:   $x10 = COPY [[COPY]](s32)
  ; CHECK-NEXT:   $x0 = RET_PSEUDO $x1, 0, implicit $x1, implicit $x10
  ret i32 %arg
}

define i32 @manyArgs(i32 %arg1, i32 %arg2, i32 %arg3, i32 %arg4, i32 %arg5, i32 %arg6, i32 %arg7, i32 %arg8, i32 %arg9, i32 %arg10) {
  ; We just return the 10th argument to ensure the stack load is translated.
  ; CHECK-LABEL: name: manyArgs
  ; CHECK: bb.1 (%ir-block.0):
  ; CHECK-NEXT:   liveins: $x10, $x11, $x12, $x13, $x14, $x15, $x16, $x17
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:_(s32) = COPY $x10
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:_(s32) = COPY $x11
  ; CHECK-NEXT:   [[COPY2:%[0-9]+]]:_(s32) = COPY $x12
  ; CHECK-NEXT:   [[COPY3:%[0-9]+]]:_(s32) = COPY $x13
  ; CHECK-NEXT:   [[COPY4:%[0-9]+]]:_(s32) = COPY $x14
  ; CHECK-NEXT:   [[COPY5:%[0-9]+]]:_(s32) = COPY $x15
  ; CHECK-NEXT:   [[COPY6:%[0-9]+]]:_(s32) = COPY $x16
  ; CHECK-NEXT:   [[COPY7:%[0-9]+]]:_(s32) = COPY $x17
  ; CHECK-NEXT:   [[FRAME_INDEX:%[0-9]+]]:_(p0) = G_FRAME_INDEX %fixed-stack.1
  ; CHECK-NEXT:   [[LOAD:%[0-9]+]]:_(s32) = G_LOAD [[FRAME_INDEX]](p0) :: (invariant load (s32) from %fixed-stack.1, align 8)
  ; CHECK-NEXT:   [[FRAME_INDEX1:%[0-9]+]]:_(p0) = G_FRAME_INDEX %fixed-stack.0
  ; CHECK-NEXT:   [[LOAD1:%[0-9]+]]:_(s32) = G_LOAD [[FRAME_INDEX1]](p0) :: (invariant load (s32) from %fixed-stack.0)
  ; CHECK-NEXT:   $x10 = COPY [[LOAD1]](s32)
  ; CHECK-NEXT:   $x0 = RET_PSEUDO $x1, 0, implicit $x1, implicit $x10
  ret i32 %arg10
}
