; NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 5
; How to run: python3 llvm/utils/update_mir_test_checks.py --llc-binary build/bin/llc llvm/test/CodeGen/Giselle/isel-only-abi.ll

; RUN: llc -mtriple giselle-- -o - %s -global-isel=1 -global-isel-abort=1 -stop-after=instruction-select -verify-machineinstrs | FileCheck %s

define void @empty() {
  ; CHECK-LABEL: name: empty
  ; CHECK: bb.1 (%ir-block.0):
  ; CHECK-NEXT:   liveins: $x1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:gpr32 = COPY $x1
  ; CHECK-NEXT:   $x1 = COPY [[COPY]]
  ; CHECK-NEXT:   RET_PSEUDO
  ret void
}
