# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 6
# How to run: python3 llvm/utils/update_mir_test_checks.py --llc-binary build/bin/llc llvm/test/CodeGen/Giselle/legalize-test-suite.mir

# RUN: llc -run-pass=legalizer %s -o - -mtriple=giselle -verify-machineinstrs | FileCheck %s
--- |
  ; ModuleID = 'llvm/test/CodeGen/Giselle/test-suite-translation.ll'
  source_filename = "llvm/test/CodeGen/Giselle/test-suite-translation.ll"
  target datalayout = "e-m:e-p:32:32:32-n32-i64:64:64-i32:32:32-i16:16:16-i1:8:8-f32:32:32-v32:32:32"
  target triple = "giselle--"

  ; Function Attrs: noinline nounwind optnone
  define dso_local i32 @main() #0 {
  entry:
    %retval = alloca i32, align 4
    store i32 0, ptr %retval, align 4
    ret i32 0
  }

  ; Function Attrs: noinline nounwind optnone
  define dso_local i32 @f0() #0 {
  entry:
    ret i32 0
  }

  ; Function Attrs: noinline nounwind optnone
  define dso_local i32 @f1() #0 {
  entry:
    %x = alloca i32, align 4
    store i32 4, ptr %x, align 4
    %0 = load i32, ptr %x, align 4
    %sub = sub nsw i32 %0, 4
    ret i32 %sub
  }

  ; Function Attrs: noinline nounwind optnone
  define dso_local i32 @f2() #0 {
  entry:
    %x = alloca i32, align 4
    %p = alloca ptr, align 4
    store i32 4, ptr %x, align 4
    store ptr %x, ptr %p, align 4
    %0 = load ptr, ptr %p, align 4
    store i32 0, ptr %0, align 4
    %1 = load ptr, ptr %p, align 4
    %2 = load i32, ptr %1, align 4
    ret i32 %2
  }

  ; Function Attrs: noinline nounwind optnone
  define dso_local i32 @f3() #0 {
  entry:
    %retval = alloca i32, align 4
    %x = alloca i32, align 4
    %p = alloca ptr, align 4
    %pp = alloca ptr, align 4
    store i32 0, ptr %x, align 4
    store ptr %x, ptr %p, align 4
    store ptr %p, ptr %pp, align 4
    %0 = load ptr, ptr %p, align 4
    %1 = load i32, ptr %0, align 4
    %tobool = icmp ne i32 %1, 0
    br i1 %tobool, label %if.then, label %if.end

  if.then:                                          ; preds = %entry
    store i32 1, ptr %retval, align 4
    br label %return

  if.end:                                           ; preds = %entry
    %2 = load ptr, ptr %pp, align 4
    %3 = load ptr, ptr %2, align 4
    %4 = load i32, ptr %3, align 4
    %tobool1 = icmp ne i32 %4, 0
    br i1 %tobool1, label %if.then2, label %if.else

  if.then2:                                         ; preds = %if.end
    store i32 1, ptr %retval, align 4
    br label %return

  if.else:                                          ; preds = %if.end
    %5 = load ptr, ptr %pp, align 4
    %6 = load ptr, ptr %5, align 4
    store i32 1, ptr %6, align 4
    br label %if.end3

  if.end3:                                          ; preds = %if.else
    %7 = load i32, ptr %x, align 4
    %tobool4 = icmp ne i32 %7, 0
    br i1 %tobool4, label %if.then5, label %if.else6

  if.then5:                                         ; preds = %if.end3
    store i32 0, ptr %retval, align 4
    br label %return

  if.else6:                                         ; preds = %if.end3
    store i32 1, ptr %retval, align 4
    br label %return

  return:                                           ; preds = %if.else6, %if.then5, %if.then2, %if.then
    %8 = load i32, ptr %retval, align 4
    ret i32 %8
  }

  ; Function Attrs: noinline nounwind optnone
  define dso_local i32 @f4() #0 {
  entry:
    %x = alloca i32, align 4
    store i32 50, ptr %x, align 4
    br label %while.cond

  while.cond:                                       ; preds = %while.body, %entry
    %0 = load i32, ptr %x, align 4
    %tobool = icmp ne i32 %0, 0
    br i1 %tobool, label %while.body, label %while.end

  while.body:                                       ; preds = %while.cond
    %1 = load i32, ptr %x, align 4
    %sub = sub nsw i32 %1, 1
    store i32 %sub, ptr %x, align 4
    br label %while.cond, !llvm.loop !2

  while.end:                                        ; preds = %while.cond
    %2 = load i32, ptr %x, align 4
    ret i32 %2
  }

  ; Function Attrs: noinline nounwind optnone
  define dso_local i32 @f5() #0 {
  entry:
    %retval = alloca i32, align 4
    %x = alloca i32, align 4
    store i32 1, ptr %x, align 4
    store i32 10, ptr %x, align 4
    br label %for.cond

  for.cond:                                         ; preds = %for.inc, %entry
    %0 = load i32, ptr %x, align 4
    %tobool = icmp ne i32 %0, 0
    br i1 %tobool, label %for.body, label %for.end

  for.body:                                         ; preds = %for.cond
    br label %for.inc

  for.inc:                                          ; preds = %for.body
    %1 = load i32, ptr %x, align 4
    %sub = sub nsw i32 %1, 1
    store i32 %sub, ptr %x, align 4
    br label %for.cond, !llvm.loop !4

  for.end:                                          ; preds = %for.cond
    %2 = load i32, ptr %x, align 4
    %tobool1 = icmp ne i32 %2, 0
    br i1 %tobool1, label %if.then, label %if.end

  if.then:                                          ; preds = %for.end
    store i32 1, ptr %retval, align 4
    br label %return

  if.end:                                           ; preds = %for.end
    store i32 10, ptr %x, align 4
    br label %for.cond2

  for.cond2:                                        ; preds = %for.body4, %if.end
    %3 = load i32, ptr %x, align 4
    %tobool3 = icmp ne i32 %3, 0
    br i1 %tobool3, label %for.body4, label %for.end6

  for.body4:                                        ; preds = %for.cond2
    %4 = load i32, ptr %x, align 4
    %sub5 = sub nsw i32 %4, 1
    store i32 %sub5, ptr %x, align 4
    br label %for.cond2, !llvm.loop !5

  for.end6:                                         ; preds = %for.cond2
    %5 = load i32, ptr %x, align 4
    store i32 %5, ptr %retval, align 4
    br label %return

  return:                                           ; preds = %for.end6, %if.then
    %6 = load i32, ptr %retval, align 4
    ret i32 %6
  }

  ; Function Attrs: noinline nounwind optnone
  define dso_local i32 @f6() #0 {
  entry:
    %x = alloca i32, align 4
    store i32 50, ptr %x, align 4
    br label %do.body

  do.body:                                          ; preds = %do.cond, %entry
    %0 = load i32, ptr %x, align 4
    %sub = sub nsw i32 %0, 1
    store i32 %sub, ptr %x, align 4
    br label %do.cond

  do.cond:                                          ; preds = %do.body
    %1 = load i32, ptr %x, align 4
    %tobool = icmp ne i32 %1, 0
    br i1 %tobool, label %do.body, label %do.end, !llvm.loop !6

  do.end:                                           ; preds = %do.cond
    %2 = load i32, ptr %x, align 4
    ret i32 %2
  }

  ; Function Attrs: noinline nounwind optnone
  define dso_local i32 @f7() #0 {
  entry:
    %x = alloca i32, align 4
    store i32 1, ptr %x, align 4
    %0 = load i32, ptr %x, align 4
    %mul = mul nsw i32 %0, 10
    store i32 %mul, ptr %x, align 4
    %1 = load i32, ptr %x, align 4
    %div = sdiv i32 %1, 2
    store i32 %div, ptr %x, align 4
    %2 = load i32, ptr %x, align 4
    %rem = srem i32 %2, 3
    store i32 %rem, ptr %x, align 4
    %3 = load i32, ptr %x, align 4
    %sub = sub nsw i32 %3, 2
    ret i32 %sub
  }

  ; Function Attrs: noinline nounwind optnone
  define dso_local i32 @f8() #0 {
  entry:
    br label %start

  start:                                            ; preds = %entry
    br label %next

  success:                                          ; preds = %foo
    ret i32 0

  next:                                             ; preds = %start
    br label %foo

  foo:                                              ; preds = %next
    br label %success
  }

  ; Function Attrs: noinline nounwind optnone
  define dso_local i32 @f9() #0 {
  entry:
    %x = alloca i32, align 4
    %y = alloca i32, align 4
    store i32 0, ptr %y, align 4
    store i32 0, ptr %x, align 4
    %0 = load i32, ptr %x, align 4
    ret i32 %0
  }

  ; Function Attrs: noinline nounwind optnone
  define dso_local i32 @f10() #0 {
  entry:
    ret i32 0
  }

  attributes #0 = { noinline nounwind optnone "no-trapping-math"="true" "stack-protector-buffer-size"="8" }

  !llvm.module.flags = !{!0}
  !llvm.ident = !{!1}

  !0 = !{i32 1, !"wchar_size", i32 4}
  !1 = !{!"clang version 22.1.0 (git@github.com:ZakyHermawan/Giselle.git 1208af47eafc4f092a20f130dd37e209ce8438a5)"}
  !2 = distinct !{!2, !3}
  !3 = !{!"llvm.loop.mustprogress"}
  !4 = distinct !{!4, !3}
  !5 = distinct !{!5, !3}
  !6 = distinct !{!6, !3}
...
---
name:            main
alignment:       1
exposesReturnsTwice: false
legalized:       false
regBankSelected: false
selected:        false
failedISel:      false
tracksRegLiveness: true
hasWinCFI:       false
noPhis:          false
isSSA:           true
noVRegs:         false
hasFakeUses:     false
callsEHReturn:   false
callsUnwindInit: false
hasEHContTarget: false
hasEHScopes:     false
hasEHFunclets:   false
isOutlined:      false
debugInstrRef:   false
failsVerification: false
tracksDebugUserValues: false
registers:
  - { id: 0, class: _, preferred-register: '', flags: [  ] }
  - { id: 1, class: _, preferred-register: '', flags: [  ] }
liveins:         []
frameInfo:
  isFrameAddressTaken: false
  isReturnAddressTaken: false
  hasStackMap:     false
  hasPatchPoint:   false
  stackSize:       0
  offsetAdjustment: 0
  maxAlignment:    4
  adjustsStack:    false
  hasCalls:        false
  stackProtector:  ''
  functionContext: ''
  maxCallFrameSize: 4294967295
  cvBytesOfCalleeSavedRegisters: 0
  hasOpaqueSPAdjustment: false
  hasVAStart:      false
  hasMustTailInVarArgFunc: false
  hasTailCall:     false
  isCalleeSavedInfoValid: false
  localFrameSize:  0
fixedStack:      []
stack:
  - { id: 0, name: retval, type: default, offset: 0, size: 4, alignment: 4,
      stack-id: default, callee-saved-register: '', callee-saved-restored: true,
      debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
entry_values:    []
callSites:       []
debugValueSubstitutions: []
constants:       []
machineFunctionInfo: {}
body:             |
  bb.1.entry:
    ; CHECK-LABEL: name: main
    ; CHECK: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; CHECK-NEXT: [[FRAME_INDEX:%[0-9]+]]:_(p0) = G_FRAME_INDEX %stack.0.retval
    ; CHECK-NEXT: G_STORE [[C]](s32), [[FRAME_INDEX]](p0) :: (store (s32) into %ir.retval)
    ; CHECK-NEXT: $x10 = COPY [[C]](s32)
    ; CHECK-NEXT: RET_PSEUDO implicit $x10
    %1:_(s32) = G_CONSTANT i32 0
    %0:_(p0) = G_FRAME_INDEX %stack.0.retval
    G_STORE %1(s32), %0(p0) :: (store (s32) into %ir.retval)
    $x10 = COPY %1(s32)
    RET_PSEUDO implicit $x10
...
---
name:            f0
alignment:       1
exposesReturnsTwice: false
legalized:       false
regBankSelected: false
selected:        false
failedISel:      false
tracksRegLiveness: true
hasWinCFI:       false
noPhis:          false
isSSA:           true
noVRegs:         false
hasFakeUses:     false
callsEHReturn:   false
callsUnwindInit: false
hasEHContTarget: false
hasEHScopes:     false
hasEHFunclets:   false
isOutlined:      false
debugInstrRef:   false
failsVerification: false
tracksDebugUserValues: false
registers:
  - { id: 0, class: _, preferred-register: '', flags: [  ] }
liveins:         []
frameInfo:
  isFrameAddressTaken: false
  isReturnAddressTaken: false
  hasStackMap:     false
  hasPatchPoint:   false
  stackSize:       0
  offsetAdjustment: 0
  maxAlignment:    1
  adjustsStack:    false
  hasCalls:        false
  stackProtector:  ''
  functionContext: ''
  maxCallFrameSize: 4294967295
  cvBytesOfCalleeSavedRegisters: 0
  hasOpaqueSPAdjustment: false
  hasVAStart:      false
  hasMustTailInVarArgFunc: false
  hasTailCall:     false
  isCalleeSavedInfoValid: false
  localFrameSize:  0
fixedStack:      []
stack:           []
entry_values:    []
callSites:       []
debugValueSubstitutions: []
constants:       []
machineFunctionInfo: {}
body:             |
  bb.1.entry:
    ; CHECK-LABEL: name: f0
    ; CHECK: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; CHECK-NEXT: $x10 = COPY [[C]](s32)
    ; CHECK-NEXT: RET_PSEUDO implicit $x10
    %0:_(s32) = G_CONSTANT i32 0
    $x10 = COPY %0(s32)
    RET_PSEUDO implicit $x10
...
---
name:            f1
alignment:       1
exposesReturnsTwice: false
legalized:       false
regBankSelected: false
selected:        false
failedISel:      false
tracksRegLiveness: true
hasWinCFI:       false
noPhis:          false
isSSA:           true
noVRegs:         false
hasFakeUses:     false
callsEHReturn:   false
callsUnwindInit: false
hasEHContTarget: false
hasEHScopes:     false
hasEHFunclets:   false
isOutlined:      false
debugInstrRef:   false
failsVerification: false
tracksDebugUserValues: false
registers:
  - { id: 0, class: _, preferred-register: '', flags: [  ] }
  - { id: 1, class: _, preferred-register: '', flags: [  ] }
  - { id: 2, class: _, preferred-register: '', flags: [  ] }
  - { id: 3, class: _, preferred-register: '', flags: [  ] }
liveins:         []
frameInfo:
  isFrameAddressTaken: false
  isReturnAddressTaken: false
  hasStackMap:     false
  hasPatchPoint:   false
  stackSize:       0
  offsetAdjustment: 0
  maxAlignment:    4
  adjustsStack:    false
  hasCalls:        false
  stackProtector:  ''
  functionContext: ''
  maxCallFrameSize: 4294967295
  cvBytesOfCalleeSavedRegisters: 0
  hasOpaqueSPAdjustment: false
  hasVAStart:      false
  hasMustTailInVarArgFunc: false
  hasTailCall:     false
  isCalleeSavedInfoValid: false
  localFrameSize:  0
fixedStack:      []
stack:
  - { id: 0, name: x, type: default, offset: 0, size: 4, alignment: 4,
      stack-id: default, callee-saved-register: '', callee-saved-restored: true,
      debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
entry_values:    []
callSites:       []
debugValueSubstitutions: []
constants:       []
machineFunctionInfo: {}
body:             |
  bb.1.entry:
    ; CHECK-LABEL: name: f1
    ; CHECK: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 4
    ; CHECK-NEXT: [[FRAME_INDEX:%[0-9]+]]:_(p0) = G_FRAME_INDEX %stack.0.x
    ; CHECK-NEXT: G_STORE [[C]](s32), [[FRAME_INDEX]](p0) :: (store (s32) into %ir.x)
    ; CHECK-NEXT: [[LOAD:%[0-9]+]]:_(s32) = G_LOAD [[FRAME_INDEX]](p0) :: (dereferenceable load (s32) from %ir.x)
    ; CHECK-NEXT: [[SUB:%[0-9]+]]:_(s32) = nsw G_SUB [[LOAD]], [[C]]
    ; CHECK-NEXT: $x10 = COPY [[SUB]](s32)
    ; CHECK-NEXT: RET_PSEUDO implicit $x10
    %1:_(s32) = G_CONSTANT i32 4
    %0:_(p0) = G_FRAME_INDEX %stack.0.x
    G_STORE %1(s32), %0(p0) :: (store (s32) into %ir.x)
    %2:_(s32) = G_LOAD %0(p0) :: (dereferenceable load (s32) from %ir.x)
    %3:_(s32) = nsw G_SUB %2, %1
    $x10 = COPY %3(s32)
    RET_PSEUDO implicit $x10
...
---
name:            f2
alignment:       1
exposesReturnsTwice: false
legalized:       false
regBankSelected: false
selected:        false
failedISel:      false
tracksRegLiveness: true
hasWinCFI:       false
noPhis:          false
isSSA:           true
noVRegs:         false
hasFakeUses:     false
callsEHReturn:   false
callsUnwindInit: false
hasEHContTarget: false
hasEHScopes:     false
hasEHFunclets:   false
isOutlined:      false
debugInstrRef:   false
failsVerification: false
tracksDebugUserValues: false
registers:
  - { id: 0, class: _, preferred-register: '', flags: [  ] }
  - { id: 1, class: _, preferred-register: '', flags: [  ] }
  - { id: 2, class: _, preferred-register: '', flags: [  ] }
  - { id: 3, class: _, preferred-register: '', flags: [  ] }
  - { id: 4, class: _, preferred-register: '', flags: [  ] }
  - { id: 5, class: _, preferred-register: '', flags: [  ] }
  - { id: 6, class: _, preferred-register: '', flags: [  ] }
liveins:         []
frameInfo:
  isFrameAddressTaken: false
  isReturnAddressTaken: false
  hasStackMap:     false
  hasPatchPoint:   false
  stackSize:       0
  offsetAdjustment: 0
  maxAlignment:    4
  adjustsStack:    false
  hasCalls:        false
  stackProtector:  ''
  functionContext: ''
  maxCallFrameSize: 4294967295
  cvBytesOfCalleeSavedRegisters: 0
  hasOpaqueSPAdjustment: false
  hasVAStart:      false
  hasMustTailInVarArgFunc: false
  hasTailCall:     false
  isCalleeSavedInfoValid: false
  localFrameSize:  0
fixedStack:      []
stack:
  - { id: 0, name: x, type: default, offset: 0, size: 4, alignment: 4,
      stack-id: default, callee-saved-register: '', callee-saved-restored: true,
      debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  - { id: 1, name: p, type: default, offset: 0, size: 4, alignment: 4,
      stack-id: default, callee-saved-register: '', callee-saved-restored: true,
      debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
entry_values:    []
callSites:       []
debugValueSubstitutions: []
constants:       []
machineFunctionInfo: {}
body:             |
  bb.1.entry:
    ; CHECK-LABEL: name: f2
    ; CHECK: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 4
    ; CHECK-NEXT: [[C1:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; CHECK-NEXT: [[FRAME_INDEX:%[0-9]+]]:_(p0) = G_FRAME_INDEX %stack.0.x
    ; CHECK-NEXT: [[FRAME_INDEX1:%[0-9]+]]:_(p0) = G_FRAME_INDEX %stack.1.p
    ; CHECK-NEXT: G_STORE [[C]](s32), [[FRAME_INDEX]](p0) :: (store (s32) into %ir.x)
    ; CHECK-NEXT: G_STORE [[FRAME_INDEX]](p0), [[FRAME_INDEX1]](p0) :: (store (p0) into %ir.p)
    ; CHECK-NEXT: [[LOAD:%[0-9]+]]:_(p0) = G_LOAD [[FRAME_INDEX1]](p0) :: (dereferenceable load (p0) from %ir.p)
    ; CHECK-NEXT: G_STORE [[C1]](s32), [[LOAD]](p0) :: (store (s32) into %ir.0)
    ; CHECK-NEXT: [[LOAD1:%[0-9]+]]:_(p0) = G_LOAD [[FRAME_INDEX1]](p0) :: (dereferenceable load (p0) from %ir.p)
    ; CHECK-NEXT: [[LOAD2:%[0-9]+]]:_(s32) = G_LOAD [[LOAD1]](p0) :: (load (s32) from %ir.1)
    ; CHECK-NEXT: $x10 = COPY [[LOAD2]](s32)
    ; CHECK-NEXT: RET_PSEUDO implicit $x10
    %2:_(s32) = G_CONSTANT i32 4
    %4:_(s32) = G_CONSTANT i32 0
    %0:_(p0) = G_FRAME_INDEX %stack.0.x
    %1:_(p0) = G_FRAME_INDEX %stack.1.p
    G_STORE %2(s32), %0(p0) :: (store (s32) into %ir.x)
    G_STORE %0(p0), %1(p0) :: (store (p0) into %ir.p)
    %3:_(p0) = G_LOAD %1(p0) :: (dereferenceable load (p0) from %ir.p)
    G_STORE %4(s32), %3(p0) :: (store (s32) into %ir.0)
    %5:_(p0) = G_LOAD %1(p0) :: (dereferenceable load (p0) from %ir.p)
    %6:_(s32) = G_LOAD %5(p0) :: (load (s32) from %ir.1)
    $x10 = COPY %6(s32)
    RET_PSEUDO implicit $x10
...
---
name:            f3
alignment:       1
exposesReturnsTwice: false
legalized:       false
regBankSelected: false
selected:        false
failedISel:      false
tracksRegLiveness: true
hasWinCFI:       false
noPhis:          false
isSSA:           true
noVRegs:         false
hasFakeUses:     false
callsEHReturn:   false
callsUnwindInit: false
hasEHContTarget: false
hasEHScopes:     false
hasEHFunclets:   false
isOutlined:      false
debugInstrRef:   false
failsVerification: false
tracksDebugUserValues: false
registers:
  - { id: 0, class: _, preferred-register: '', flags: [  ] }
  - { id: 1, class: _, preferred-register: '', flags: [  ] }
  - { id: 2, class: _, preferred-register: '', flags: [  ] }
  - { id: 3, class: _, preferred-register: '', flags: [  ] }
  - { id: 4, class: _, preferred-register: '', flags: [  ] }
  - { id: 5, class: _, preferred-register: '', flags: [  ] }
  - { id: 6, class: _, preferred-register: '', flags: [  ] }
  - { id: 7, class: _, preferred-register: '', flags: [  ] }
  - { id: 8, class: _, preferred-register: '', flags: [  ] }
  - { id: 9, class: _, preferred-register: '', flags: [  ] }
  - { id: 10, class: _, preferred-register: '', flags: [  ] }
  - { id: 11, class: _, preferred-register: '', flags: [  ] }
  - { id: 12, class: _, preferred-register: '', flags: [  ] }
  - { id: 13, class: _, preferred-register: '', flags: [  ] }
  - { id: 14, class: _, preferred-register: '', flags: [  ] }
  - { id: 15, class: _, preferred-register: '', flags: [  ] }
  - { id: 16, class: _, preferred-register: '', flags: [  ] }
  - { id: 17, class: _, preferred-register: '', flags: [  ] }
liveins:         []
frameInfo:
  isFrameAddressTaken: false
  isReturnAddressTaken: false
  hasStackMap:     false
  hasPatchPoint:   false
  stackSize:       0
  offsetAdjustment: 0
  maxAlignment:    4
  adjustsStack:    false
  hasCalls:        false
  stackProtector:  ''
  functionContext: ''
  maxCallFrameSize: 4294967295
  cvBytesOfCalleeSavedRegisters: 0
  hasOpaqueSPAdjustment: false
  hasVAStart:      false
  hasMustTailInVarArgFunc: false
  hasTailCall:     false
  isCalleeSavedInfoValid: false
  localFrameSize:  0
fixedStack:      []
stack:
  - { id: 0, name: retval, type: default, offset: 0, size: 4, alignment: 4,
      stack-id: default, callee-saved-register: '', callee-saved-restored: true,
      debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  - { id: 1, name: x, type: default, offset: 0, size: 4, alignment: 4,
      stack-id: default, callee-saved-register: '', callee-saved-restored: true,
      debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  - { id: 2, name: p, type: default, offset: 0, size: 4, alignment: 4,
      stack-id: default, callee-saved-register: '', callee-saved-restored: true,
      debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  - { id: 3, name: pp, type: default, offset: 0, size: 4, alignment: 4,
      stack-id: default, callee-saved-register: '', callee-saved-restored: true,
      debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
entry_values:    []
callSites:       []
debugValueSubstitutions: []
constants:       []
machineFunctionInfo: {}
body:             |
  ; CHECK-LABEL: name: f3
  ; CHECK: bb.0.entry:
  ; CHECK-NEXT:   successors: %bb.1(0x40000000), %bb.2(0x40000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
  ; CHECK-NEXT:   [[C1:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
  ; CHECK-NEXT:   [[FRAME_INDEX:%[0-9]+]]:_(p0) = G_FRAME_INDEX %stack.0.retval
  ; CHECK-NEXT:   [[FRAME_INDEX1:%[0-9]+]]:_(p0) = G_FRAME_INDEX %stack.1.x
  ; CHECK-NEXT:   [[FRAME_INDEX2:%[0-9]+]]:_(p0) = G_FRAME_INDEX %stack.2.p
  ; CHECK-NEXT:   [[FRAME_INDEX3:%[0-9]+]]:_(p0) = G_FRAME_INDEX %stack.3.pp
  ; CHECK-NEXT:   G_STORE [[C]](s32), [[FRAME_INDEX1]](p0) :: (store (s32) into %ir.x)
  ; CHECK-NEXT:   G_STORE [[FRAME_INDEX1]](p0), [[FRAME_INDEX2]](p0) :: (store (p0) into %ir.p)
  ; CHECK-NEXT:   G_STORE [[FRAME_INDEX2]](p0), [[FRAME_INDEX3]](p0) :: (store (p0) into %ir.pp)
  ; CHECK-NEXT:   [[LOAD:%[0-9]+]]:_(p0) = G_LOAD [[FRAME_INDEX2]](p0) :: (dereferenceable load (p0) from %ir.p)
  ; CHECK-NEXT:   [[LOAD1:%[0-9]+]]:_(s32) = G_LOAD [[LOAD]](p0) :: (load (s32) from %ir.0)
  ; CHECK-NEXT:   [[ICMP:%[0-9]+]]:_(s16) = G_ICMP intpred(ne), [[LOAD1]](s32), [[C]]
  ; CHECK-NEXT:   [[TRUNC:%[0-9]+]]:_(s1) = G_TRUNC [[ICMP]](s16)
  ; CHECK-NEXT:   G_BRCOND [[TRUNC]](s1), %bb.1
  ; CHECK-NEXT:   G_BR %bb.2
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1.if.then:
  ; CHECK-NEXT:   successors: %bb.8(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   G_STORE [[C1]](s32), [[FRAME_INDEX]](p0) :: (store (s32) into %ir.retval)
  ; CHECK-NEXT:   G_BR %bb.8
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2.if.end:
  ; CHECK-NEXT:   successors: %bb.3(0x40000000), %bb.4(0x40000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[LOAD2:%[0-9]+]]:_(p0) = G_LOAD [[FRAME_INDEX3]](p0) :: (dereferenceable load (p0) from %ir.pp)
  ; CHECK-NEXT:   [[LOAD3:%[0-9]+]]:_(p0) = G_LOAD [[LOAD2]](p0) :: (load (p0) from %ir.2)
  ; CHECK-NEXT:   [[LOAD4:%[0-9]+]]:_(s32) = G_LOAD [[LOAD3]](p0) :: (load (s32) from %ir.3)
  ; CHECK-NEXT:   [[ICMP1:%[0-9]+]]:_(s16) = G_ICMP intpred(ne), [[LOAD4]](s32), [[C]]
  ; CHECK-NEXT:   [[TRUNC1:%[0-9]+]]:_(s1) = G_TRUNC [[ICMP1]](s16)
  ; CHECK-NEXT:   G_BRCOND [[TRUNC1]](s1), %bb.3
  ; CHECK-NEXT:   G_BR %bb.4
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.3.if.then2:
  ; CHECK-NEXT:   successors: %bb.8(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   G_STORE [[C1]](s32), [[FRAME_INDEX]](p0) :: (store (s32) into %ir.retval)
  ; CHECK-NEXT:   G_BR %bb.8
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.4.if.else:
  ; CHECK-NEXT:   successors: %bb.5(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[LOAD5:%[0-9]+]]:_(p0) = G_LOAD [[FRAME_INDEX3]](p0) :: (dereferenceable load (p0) from %ir.pp)
  ; CHECK-NEXT:   [[LOAD6:%[0-9]+]]:_(p0) = G_LOAD [[LOAD5]](p0) :: (load (p0) from %ir.5)
  ; CHECK-NEXT:   G_STORE [[C1]](s32), [[LOAD6]](p0) :: (store (s32) into %ir.6)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.5.if.end3:
  ; CHECK-NEXT:   successors: %bb.6(0x40000000), %bb.7(0x40000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[LOAD7:%[0-9]+]]:_(s32) = G_LOAD [[FRAME_INDEX1]](p0) :: (dereferenceable load (s32) from %ir.x)
  ; CHECK-NEXT:   [[ICMP2:%[0-9]+]]:_(s16) = G_ICMP intpred(ne), [[LOAD7]](s32), [[C]]
  ; CHECK-NEXT:   [[TRUNC2:%[0-9]+]]:_(s1) = G_TRUNC [[ICMP2]](s16)
  ; CHECK-NEXT:   G_BRCOND [[TRUNC2]](s1), %bb.6
  ; CHECK-NEXT:   G_BR %bb.7
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.6.if.then5:
  ; CHECK-NEXT:   successors: %bb.8(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   G_STORE [[C]](s32), [[FRAME_INDEX]](p0) :: (store (s32) into %ir.retval)
  ; CHECK-NEXT:   G_BR %bb.8
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.7.if.else6:
  ; CHECK-NEXT:   successors: %bb.8(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   G_STORE [[C1]](s32), [[FRAME_INDEX]](p0) :: (store (s32) into %ir.retval)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.8.return:
  ; CHECK-NEXT:   [[LOAD8:%[0-9]+]]:_(s32) = G_LOAD [[FRAME_INDEX]](p0) :: (dereferenceable load (s32) from %ir.retval)
  ; CHECK-NEXT:   $x10 = COPY [[LOAD8]](s32)
  ; CHECK-NEXT:   RET_PSEUDO implicit $x10
  bb.1.entry:
    successors: %bb.2(0x40000000), %bb.3(0x40000000)

    %4:_(s32) = G_CONSTANT i32 0
    %14:_(s32) = G_CONSTANT i32 1
    %0:_(p0) = G_FRAME_INDEX %stack.0.retval
    %1:_(p0) = G_FRAME_INDEX %stack.1.x
    %2:_(p0) = G_FRAME_INDEX %stack.2.p
    %3:_(p0) = G_FRAME_INDEX %stack.3.pp
    G_STORE %4(s32), %1(p0) :: (store (s32) into %ir.x)
    G_STORE %1(p0), %2(p0) :: (store (p0) into %ir.p)
    G_STORE %2(p0), %3(p0) :: (store (p0) into %ir.pp)
    %5:_(p0) = G_LOAD %2(p0) :: (dereferenceable load (p0) from %ir.p)
    %6:_(s32) = G_LOAD %5(p0) :: (load (s32) from %ir.0)
    %7:_(s1) = G_ICMP intpred(ne), %6(s32), %4
    G_BRCOND %7(s1), %bb.2
    G_BR %bb.3

  bb.2.if.then:
    successors: %bb.9(0x80000000)

    G_STORE %14(s32), %0(p0) :: (store (s32) into %ir.retval)
    G_BR %bb.9

  bb.3.if.end:
    successors: %bb.4(0x40000000), %bb.5(0x40000000)

    %8:_(p0) = G_LOAD %3(p0) :: (dereferenceable load (p0) from %ir.pp)
    %9:_(p0) = G_LOAD %8(p0) :: (load (p0) from %ir.2)
    %10:_(s32) = G_LOAD %9(p0) :: (load (s32) from %ir.3)
    %11:_(s1) = G_ICMP intpred(ne), %10(s32), %4
    G_BRCOND %11(s1), %bb.4
    G_BR %bb.5

  bb.4.if.then2:
    successors: %bb.9(0x80000000)

    G_STORE %14(s32), %0(p0) :: (store (s32) into %ir.retval)
    G_BR %bb.9

  bb.5.if.else:
    successors: %bb.6(0x80000000)

    %12:_(p0) = G_LOAD %3(p0) :: (dereferenceable load (p0) from %ir.pp)
    %13:_(p0) = G_LOAD %12(p0) :: (load (p0) from %ir.5)
    G_STORE %14(s32), %13(p0) :: (store (s32) into %ir.6)

  bb.6.if.end3:
    successors: %bb.7(0x40000000), %bb.8(0x40000000)

    %15:_(s32) = G_LOAD %1(p0) :: (dereferenceable load (s32) from %ir.x)
    %16:_(s1) = G_ICMP intpred(ne), %15(s32), %4
    G_BRCOND %16(s1), %bb.7
    G_BR %bb.8

  bb.7.if.then5:
    successors: %bb.9(0x80000000)

    G_STORE %4(s32), %0(p0) :: (store (s32) into %ir.retval)
    G_BR %bb.9

  bb.8.if.else6:
    successors: %bb.9(0x80000000)

    G_STORE %14(s32), %0(p0) :: (store (s32) into %ir.retval)

  bb.9.return:
    %17:_(s32) = G_LOAD %0(p0) :: (dereferenceable load (s32) from %ir.retval)
    $x10 = COPY %17(s32)
    RET_PSEUDO implicit $x10
...
---
name:            f4
alignment:       1
exposesReturnsTwice: false
legalized:       false
regBankSelected: false
selected:        false
failedISel:      false
tracksRegLiveness: true
hasWinCFI:       false
noPhis:          false
isSSA:           true
noVRegs:         false
hasFakeUses:     false
callsEHReturn:   false
callsUnwindInit: false
hasEHContTarget: false
hasEHScopes:     false
hasEHFunclets:   false
isOutlined:      false
debugInstrRef:   false
failsVerification: false
tracksDebugUserValues: false
registers:
  - { id: 0, class: _, preferred-register: '', flags: [  ] }
  - { id: 1, class: _, preferred-register: '', flags: [  ] }
  - { id: 2, class: _, preferred-register: '', flags: [  ] }
  - { id: 3, class: _, preferred-register: '', flags: [  ] }
  - { id: 4, class: _, preferred-register: '', flags: [  ] }
  - { id: 5, class: _, preferred-register: '', flags: [  ] }
  - { id: 6, class: _, preferred-register: '', flags: [  ] }
  - { id: 7, class: _, preferred-register: '', flags: [  ] }
  - { id: 8, class: _, preferred-register: '', flags: [  ] }
liveins:         []
frameInfo:
  isFrameAddressTaken: false
  isReturnAddressTaken: false
  hasStackMap:     false
  hasPatchPoint:   false
  stackSize:       0
  offsetAdjustment: 0
  maxAlignment:    4
  adjustsStack:    false
  hasCalls:        false
  stackProtector:  ''
  functionContext: ''
  maxCallFrameSize: 4294967295
  cvBytesOfCalleeSavedRegisters: 0
  hasOpaqueSPAdjustment: false
  hasVAStart:      false
  hasMustTailInVarArgFunc: false
  hasTailCall:     false
  isCalleeSavedInfoValid: false
  localFrameSize:  0
fixedStack:      []
stack:
  - { id: 0, name: x, type: default, offset: 0, size: 4, alignment: 4,
      stack-id: default, callee-saved-register: '', callee-saved-restored: true,
      debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
entry_values:    []
callSites:       []
debugValueSubstitutions: []
constants:       []
machineFunctionInfo: {}
body:             |
  ; CHECK-LABEL: name: f4
  ; CHECK: bb.0.entry:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 50
  ; CHECK-NEXT:   [[C1:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
  ; CHECK-NEXT:   [[C2:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
  ; CHECK-NEXT:   [[FRAME_INDEX:%[0-9]+]]:_(p0) = G_FRAME_INDEX %stack.0.x
  ; CHECK-NEXT:   G_STORE [[C]](s32), [[FRAME_INDEX]](p0) :: (store (s32) into %ir.x)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1.while.cond:
  ; CHECK-NEXT:   successors: %bb.2(0x40000000), %bb.3(0x40000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[LOAD:%[0-9]+]]:_(s32) = G_LOAD [[FRAME_INDEX]](p0) :: (dereferenceable load (s32) from %ir.x)
  ; CHECK-NEXT:   [[ICMP:%[0-9]+]]:_(s16) = G_ICMP intpred(ne), [[LOAD]](s32), [[C1]]
  ; CHECK-NEXT:   [[TRUNC:%[0-9]+]]:_(s1) = G_TRUNC [[ICMP]](s16)
  ; CHECK-NEXT:   G_BRCOND [[TRUNC]](s1), %bb.2
  ; CHECK-NEXT:   G_BR %bb.3
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2.while.body:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[LOAD1:%[0-9]+]]:_(s32) = G_LOAD [[FRAME_INDEX]](p0) :: (dereferenceable load (s32) from %ir.x)
  ; CHECK-NEXT:   [[SUB:%[0-9]+]]:_(s32) = nsw G_SUB [[LOAD1]], [[C2]]
  ; CHECK-NEXT:   G_STORE [[SUB]](s32), [[FRAME_INDEX]](p0) :: (store (s32) into %ir.x)
  ; CHECK-NEXT:   G_BR %bb.1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.3.while.end:
  ; CHECK-NEXT:   [[LOAD2:%[0-9]+]]:_(s32) = G_LOAD [[FRAME_INDEX]](p0) :: (dereferenceable load (s32) from %ir.x)
  ; CHECK-NEXT:   $x10 = COPY [[LOAD2]](s32)
  ; CHECK-NEXT:   RET_PSEUDO implicit $x10
  bb.1.entry:
    successors: %bb.2(0x80000000)

    %1:_(s32) = G_CONSTANT i32 50
    %3:_(s32) = G_CONSTANT i32 0
    %7:_(s32) = G_CONSTANT i32 1
    %0:_(p0) = G_FRAME_INDEX %stack.0.x
    G_STORE %1(s32), %0(p0) :: (store (s32) into %ir.x)

  bb.2.while.cond:
    successors: %bb.3(0x40000000), %bb.4(0x40000000)

    %2:_(s32) = G_LOAD %0(p0) :: (dereferenceable load (s32) from %ir.x)
    %4:_(s1) = G_ICMP intpred(ne), %2(s32), %3
    G_BRCOND %4(s1), %bb.3
    G_BR %bb.4

  bb.3.while.body:
    successors: %bb.2(0x80000000)

    %6:_(s32) = G_LOAD %0(p0) :: (dereferenceable load (s32) from %ir.x)
    %8:_(s32) = nsw G_SUB %6, %7
    G_STORE %8(s32), %0(p0) :: (store (s32) into %ir.x)
    G_BR %bb.2

  bb.4.while.end:
    %5:_(s32) = G_LOAD %0(p0) :: (dereferenceable load (s32) from %ir.x)
    $x10 = COPY %5(s32)
    RET_PSEUDO implicit $x10
...
---
name:            f5
alignment:       1
exposesReturnsTwice: false
legalized:       false
regBankSelected: false
selected:        false
failedISel:      false
tracksRegLiveness: true
hasWinCFI:       false
noPhis:          false
isSSA:           true
noVRegs:         false
hasFakeUses:     false
callsEHReturn:   false
callsUnwindInit: false
hasEHContTarget: false
hasEHScopes:     false
hasEHFunclets:   false
isOutlined:      false
debugInstrRef:   false
failsVerification: false
tracksDebugUserValues: false
registers:
  - { id: 0, class: _, preferred-register: '', flags: [  ] }
  - { id: 1, class: _, preferred-register: '', flags: [  ] }
  - { id: 2, class: _, preferred-register: '', flags: [  ] }
  - { id: 3, class: _, preferred-register: '', flags: [  ] }
  - { id: 4, class: _, preferred-register: '', flags: [  ] }
  - { id: 5, class: _, preferred-register: '', flags: [  ] }
  - { id: 6, class: _, preferred-register: '', flags: [  ] }
  - { id: 7, class: _, preferred-register: '', flags: [  ] }
  - { id: 8, class: _, preferred-register: '', flags: [  ] }
  - { id: 9, class: _, preferred-register: '', flags: [  ] }
  - { id: 10, class: _, preferred-register: '', flags: [  ] }
  - { id: 11, class: _, preferred-register: '', flags: [  ] }
  - { id: 12, class: _, preferred-register: '', flags: [  ] }
  - { id: 13, class: _, preferred-register: '', flags: [  ] }
  - { id: 14, class: _, preferred-register: '', flags: [  ] }
  - { id: 15, class: _, preferred-register: '', flags: [  ] }
  - { id: 16, class: _, preferred-register: '', flags: [  ] }
liveins:         []
frameInfo:
  isFrameAddressTaken: false
  isReturnAddressTaken: false
  hasStackMap:     false
  hasPatchPoint:   false
  stackSize:       0
  offsetAdjustment: 0
  maxAlignment:    4
  adjustsStack:    false
  hasCalls:        false
  stackProtector:  ''
  functionContext: ''
  maxCallFrameSize: 4294967295
  cvBytesOfCalleeSavedRegisters: 0
  hasOpaqueSPAdjustment: false
  hasVAStart:      false
  hasMustTailInVarArgFunc: false
  hasTailCall:     false
  isCalleeSavedInfoValid: false
  localFrameSize:  0
fixedStack:      []
stack:
  - { id: 0, name: retval, type: default, offset: 0, size: 4, alignment: 4,
      stack-id: default, callee-saved-register: '', callee-saved-restored: true,
      debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  - { id: 1, name: x, type: default, offset: 0, size: 4, alignment: 4,
      stack-id: default, callee-saved-register: '', callee-saved-restored: true,
      debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
entry_values:    []
callSites:       []
debugValueSubstitutions: []
constants:       []
machineFunctionInfo: {}
body:             |
  ; CHECK-LABEL: name: f5
  ; CHECK: bb.0.entry:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
  ; CHECK-NEXT:   [[C1:%[0-9]+]]:_(s32) = G_CONSTANT i32 10
  ; CHECK-NEXT:   [[C2:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
  ; CHECK-NEXT:   [[FRAME_INDEX:%[0-9]+]]:_(p0) = G_FRAME_INDEX %stack.0.retval
  ; CHECK-NEXT:   [[FRAME_INDEX1:%[0-9]+]]:_(p0) = G_FRAME_INDEX %stack.1.x
  ; CHECK-NEXT:   G_STORE [[C]](s32), [[FRAME_INDEX1]](p0) :: (store (s32) into %ir.x)
  ; CHECK-NEXT:   G_STORE [[C1]](s32), [[FRAME_INDEX1]](p0) :: (store (s32) into %ir.x)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1.for.cond:
  ; CHECK-NEXT:   successors: %bb.2(0x40000000), %bb.4(0x40000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[LOAD:%[0-9]+]]:_(s32) = G_LOAD [[FRAME_INDEX1]](p0) :: (dereferenceable load (s32) from %ir.x)
  ; CHECK-NEXT:   [[ICMP:%[0-9]+]]:_(s16) = G_ICMP intpred(ne), [[LOAD]](s32), [[C2]]
  ; CHECK-NEXT:   [[TRUNC:%[0-9]+]]:_(s1) = G_TRUNC [[ICMP]](s16)
  ; CHECK-NEXT:   G_BRCOND [[TRUNC]](s1), %bb.2
  ; CHECK-NEXT:   G_BR %bb.4
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2.for.body:
  ; CHECK-NEXT:   successors: %bb.3(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.3.for.inc:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[LOAD1:%[0-9]+]]:_(s32) = G_LOAD [[FRAME_INDEX1]](p0) :: (dereferenceable load (s32) from %ir.x)
  ; CHECK-NEXT:   [[SUB:%[0-9]+]]:_(s32) = nsw G_SUB [[LOAD1]], [[C]]
  ; CHECK-NEXT:   G_STORE [[SUB]](s32), [[FRAME_INDEX1]](p0) :: (store (s32) into %ir.x)
  ; CHECK-NEXT:   G_BR %bb.1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.4.for.end:
  ; CHECK-NEXT:   successors: %bb.5(0x40000000), %bb.6(0x40000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[LOAD2:%[0-9]+]]:_(s32) = G_LOAD [[FRAME_INDEX1]](p0) :: (dereferenceable load (s32) from %ir.x)
  ; CHECK-NEXT:   [[ICMP1:%[0-9]+]]:_(s16) = G_ICMP intpred(ne), [[LOAD2]](s32), [[C2]]
  ; CHECK-NEXT:   [[TRUNC1:%[0-9]+]]:_(s1) = G_TRUNC [[ICMP1]](s16)
  ; CHECK-NEXT:   G_BRCOND [[TRUNC1]](s1), %bb.5
  ; CHECK-NEXT:   G_BR %bb.6
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.5.if.then:
  ; CHECK-NEXT:   successors: %bb.10(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   G_STORE [[C]](s32), [[FRAME_INDEX]](p0) :: (store (s32) into %ir.retval)
  ; CHECK-NEXT:   G_BR %bb.10
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.6.if.end:
  ; CHECK-NEXT:   successors: %bb.7(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   G_STORE [[C1]](s32), [[FRAME_INDEX1]](p0) :: (store (s32) into %ir.x)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.7.for.cond2:
  ; CHECK-NEXT:   successors: %bb.8(0x40000000), %bb.9(0x40000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[LOAD3:%[0-9]+]]:_(s32) = G_LOAD [[FRAME_INDEX1]](p0) :: (dereferenceable load (s32) from %ir.x)
  ; CHECK-NEXT:   [[ICMP2:%[0-9]+]]:_(s16) = G_ICMP intpred(ne), [[LOAD3]](s32), [[C2]]
  ; CHECK-NEXT:   [[TRUNC2:%[0-9]+]]:_(s1) = G_TRUNC [[ICMP2]](s16)
  ; CHECK-NEXT:   G_BRCOND [[TRUNC2]](s1), %bb.8
  ; CHECK-NEXT:   G_BR %bb.9
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.8.for.body4:
  ; CHECK-NEXT:   successors: %bb.7(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[LOAD4:%[0-9]+]]:_(s32) = G_LOAD [[FRAME_INDEX1]](p0) :: (dereferenceable load (s32) from %ir.x)
  ; CHECK-NEXT:   [[SUB1:%[0-9]+]]:_(s32) = nsw G_SUB [[LOAD4]], [[C]]
  ; CHECK-NEXT:   G_STORE [[SUB1]](s32), [[FRAME_INDEX1]](p0) :: (store (s32) into %ir.x)
  ; CHECK-NEXT:   G_BR %bb.7
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.9.for.end6:
  ; CHECK-NEXT:   successors: %bb.10(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[LOAD5:%[0-9]+]]:_(s32) = G_LOAD [[FRAME_INDEX1]](p0) :: (dereferenceable load (s32) from %ir.x)
  ; CHECK-NEXT:   G_STORE [[LOAD5]](s32), [[FRAME_INDEX]](p0) :: (store (s32) into %ir.retval)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.10.return:
  ; CHECK-NEXT:   [[LOAD6:%[0-9]+]]:_(s32) = G_LOAD [[FRAME_INDEX]](p0) :: (dereferenceable load (s32) from %ir.retval)
  ; CHECK-NEXT:   $x10 = COPY [[LOAD6]](s32)
  ; CHECK-NEXT:   RET_PSEUDO implicit $x10
  bb.1.entry:
    successors: %bb.2(0x80000000)

    %2:_(s32) = G_CONSTANT i32 1
    %3:_(s32) = G_CONSTANT i32 10
    %5:_(s32) = G_CONSTANT i32 0
    %0:_(p0) = G_FRAME_INDEX %stack.0.retval
    %1:_(p0) = G_FRAME_INDEX %stack.1.x
    G_STORE %2(s32), %1(p0) :: (store (s32) into %ir.x)
    G_STORE %3(s32), %1(p0) :: (store (s32) into %ir.x)

  bb.2.for.cond:
    successors: %bb.3(0x40000000), %bb.5(0x40000000)

    %4:_(s32) = G_LOAD %1(p0) :: (dereferenceable load (s32) from %ir.x)
    %6:_(s1) = G_ICMP intpred(ne), %4(s32), %5
    G_BRCOND %6(s1), %bb.3
    G_BR %bb.5

  bb.3.for.body:
    successors: %bb.4(0x80000000)

  bb.4.for.inc:
    successors: %bb.2(0x80000000)

    %15:_(s32) = G_LOAD %1(p0) :: (dereferenceable load (s32) from %ir.x)
    %16:_(s32) = nsw G_SUB %15, %2
    G_STORE %16(s32), %1(p0) :: (store (s32) into %ir.x)
    G_BR %bb.2

  bb.5.for.end:
    successors: %bb.6(0x40000000), %bb.7(0x40000000)

    %7:_(s32) = G_LOAD %1(p0) :: (dereferenceable load (s32) from %ir.x)
    %8:_(s1) = G_ICMP intpred(ne), %7(s32), %5
    G_BRCOND %8(s1), %bb.6
    G_BR %bb.7

  bb.6.if.then:
    successors: %bb.11(0x80000000)

    G_STORE %2(s32), %0(p0) :: (store (s32) into %ir.retval)
    G_BR %bb.11

  bb.7.if.end:
    successors: %bb.8(0x80000000)

    G_STORE %3(s32), %1(p0) :: (store (s32) into %ir.x)

  bb.8.for.cond2:
    successors: %bb.9(0x40000000), %bb.10(0x40000000)

    %9:_(s32) = G_LOAD %1(p0) :: (dereferenceable load (s32) from %ir.x)
    %10:_(s1) = G_ICMP intpred(ne), %9(s32), %5
    G_BRCOND %10(s1), %bb.9
    G_BR %bb.10

  bb.9.for.body4:
    successors: %bb.8(0x80000000)

    %12:_(s32) = G_LOAD %1(p0) :: (dereferenceable load (s32) from %ir.x)
    %13:_(s32) = nsw G_SUB %12, %2
    G_STORE %13(s32), %1(p0) :: (store (s32) into %ir.x)
    G_BR %bb.8

  bb.10.for.end6:
    successors: %bb.11(0x80000000)

    %11:_(s32) = G_LOAD %1(p0) :: (dereferenceable load (s32) from %ir.x)
    G_STORE %11(s32), %0(p0) :: (store (s32) into %ir.retval)

  bb.11.return:
    %14:_(s32) = G_LOAD %0(p0) :: (dereferenceable load (s32) from %ir.retval)
    $x10 = COPY %14(s32)
    RET_PSEUDO implicit $x10
...
---
name:            f6
alignment:       1
exposesReturnsTwice: false
legalized:       false
regBankSelected: false
selected:        false
failedISel:      false
tracksRegLiveness: true
hasWinCFI:       false
noPhis:          false
isSSA:           true
noVRegs:         false
hasFakeUses:     false
callsEHReturn:   false
callsUnwindInit: false
hasEHContTarget: false
hasEHScopes:     false
hasEHFunclets:   false
isOutlined:      false
debugInstrRef:   false
failsVerification: false
tracksDebugUserValues: false
registers:
  - { id: 0, class: _, preferred-register: '', flags: [  ] }
  - { id: 1, class: _, preferred-register: '', flags: [  ] }
  - { id: 2, class: _, preferred-register: '', flags: [  ] }
  - { id: 3, class: _, preferred-register: '', flags: [  ] }
  - { id: 4, class: _, preferred-register: '', flags: [  ] }
  - { id: 5, class: _, preferred-register: '', flags: [  ] }
  - { id: 6, class: _, preferred-register: '', flags: [  ] }
  - { id: 7, class: _, preferred-register: '', flags: [  ] }
  - { id: 8, class: _, preferred-register: '', flags: [  ] }
liveins:         []
frameInfo:
  isFrameAddressTaken: false
  isReturnAddressTaken: false
  hasStackMap:     false
  hasPatchPoint:   false
  stackSize:       0
  offsetAdjustment: 0
  maxAlignment:    4
  adjustsStack:    false
  hasCalls:        false
  stackProtector:  ''
  functionContext: ''
  maxCallFrameSize: 4294967295
  cvBytesOfCalleeSavedRegisters: 0
  hasOpaqueSPAdjustment: false
  hasVAStart:      false
  hasMustTailInVarArgFunc: false
  hasTailCall:     false
  isCalleeSavedInfoValid: false
  localFrameSize:  0
fixedStack:      []
stack:
  - { id: 0, name: x, type: default, offset: 0, size: 4, alignment: 4,
      stack-id: default, callee-saved-register: '', callee-saved-restored: true,
      debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
entry_values:    []
callSites:       []
debugValueSubstitutions: []
constants:       []
machineFunctionInfo: {}
body:             |
  ; CHECK-LABEL: name: f6
  ; CHECK: bb.0.entry:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 50
  ; CHECK-NEXT:   [[C1:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
  ; CHECK-NEXT:   [[C2:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
  ; CHECK-NEXT:   [[FRAME_INDEX:%[0-9]+]]:_(p0) = G_FRAME_INDEX %stack.0.x
  ; CHECK-NEXT:   G_STORE [[C]](s32), [[FRAME_INDEX]](p0) :: (store (s32) into %ir.x)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1.do.body:
  ; CHECK-NEXT:   successors: %bb.2(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[LOAD:%[0-9]+]]:_(s32) = G_LOAD [[FRAME_INDEX]](p0) :: (dereferenceable load (s32) from %ir.x)
  ; CHECK-NEXT:   [[SUB:%[0-9]+]]:_(s32) = nsw G_SUB [[LOAD]], [[C1]]
  ; CHECK-NEXT:   G_STORE [[SUB]](s32), [[FRAME_INDEX]](p0) :: (store (s32) into %ir.x)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2.do.cond:
  ; CHECK-NEXT:   successors: %bb.1(0x40000000), %bb.3(0x40000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[LOAD1:%[0-9]+]]:_(s32) = G_LOAD [[FRAME_INDEX]](p0) :: (dereferenceable load (s32) from %ir.x)
  ; CHECK-NEXT:   [[ICMP:%[0-9]+]]:_(s16) = G_ICMP intpred(ne), [[LOAD1]](s32), [[C2]]
  ; CHECK-NEXT:   [[TRUNC:%[0-9]+]]:_(s1) = G_TRUNC [[ICMP]](s16)
  ; CHECK-NEXT:   G_BRCOND [[TRUNC]](s1), %bb.1
  ; CHECK-NEXT:   G_BR %bb.3
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.3.do.end:
  ; CHECK-NEXT:   [[LOAD2:%[0-9]+]]:_(s32) = G_LOAD [[FRAME_INDEX]](p0) :: (dereferenceable load (s32) from %ir.x)
  ; CHECK-NEXT:   $x10 = COPY [[LOAD2]](s32)
  ; CHECK-NEXT:   RET_PSEUDO implicit $x10
  bb.1.entry:
    successors: %bb.2(0x80000000)

    %1:_(s32) = G_CONSTANT i32 50
    %3:_(s32) = G_CONSTANT i32 1
    %6:_(s32) = G_CONSTANT i32 0
    %0:_(p0) = G_FRAME_INDEX %stack.0.x
    G_STORE %1(s32), %0(p0) :: (store (s32) into %ir.x)

  bb.2.do.body:
    successors: %bb.3(0x80000000)

    %2:_(s32) = G_LOAD %0(p0) :: (dereferenceable load (s32) from %ir.x)
    %4:_(s32) = nsw G_SUB %2, %3
    G_STORE %4(s32), %0(p0) :: (store (s32) into %ir.x)

  bb.3.do.cond:
    successors: %bb.2(0x40000000), %bb.4(0x40000000)

    %5:_(s32) = G_LOAD %0(p0) :: (dereferenceable load (s32) from %ir.x)
    %7:_(s1) = G_ICMP intpred(ne), %5(s32), %6
    G_BRCOND %7(s1), %bb.2
    G_BR %bb.4

  bb.4.do.end:
    %8:_(s32) = G_LOAD %0(p0) :: (dereferenceable load (s32) from %ir.x)
    $x10 = COPY %8(s32)
    RET_PSEUDO implicit $x10
...
---
name:            f7
alignment:       1
exposesReturnsTwice: false
legalized:       false
regBankSelected: false
selected:        false
failedISel:      false
tracksRegLiveness: true
hasWinCFI:       false
noPhis:          false
isSSA:           true
noVRegs:         false
hasFakeUses:     false
callsEHReturn:   false
callsUnwindInit: false
hasEHContTarget: false
hasEHScopes:     false
hasEHFunclets:   false
isOutlined:      false
debugInstrRef:   false
failsVerification: false
tracksDebugUserValues: false
registers:
  - { id: 0, class: _, preferred-register: '', flags: [  ] }
  - { id: 1, class: _, preferred-register: '', flags: [  ] }
  - { id: 2, class: _, preferred-register: '', flags: [  ] }
  - { id: 3, class: _, preferred-register: '', flags: [  ] }
  - { id: 4, class: _, preferred-register: '', flags: [  ] }
  - { id: 5, class: _, preferred-register: '', flags: [  ] }
  - { id: 6, class: _, preferred-register: '', flags: [  ] }
  - { id: 7, class: _, preferred-register: '', flags: [  ] }
  - { id: 8, class: _, preferred-register: '', flags: [  ] }
  - { id: 9, class: _, preferred-register: '', flags: [  ] }
  - { id: 10, class: _, preferred-register: '', flags: [  ] }
  - { id: 11, class: _, preferred-register: '', flags: [  ] }
  - { id: 12, class: _, preferred-register: '', flags: [  ] }
liveins:         []
frameInfo:
  isFrameAddressTaken: false
  isReturnAddressTaken: false
  hasStackMap:     false
  hasPatchPoint:   false
  stackSize:       0
  offsetAdjustment: 0
  maxAlignment:    4
  adjustsStack:    false
  hasCalls:        false
  stackProtector:  ''
  functionContext: ''
  maxCallFrameSize: 4294967295
  cvBytesOfCalleeSavedRegisters: 0
  hasOpaqueSPAdjustment: false
  hasVAStart:      false
  hasMustTailInVarArgFunc: false
  hasTailCall:     false
  isCalleeSavedInfoValid: false
  localFrameSize:  0
fixedStack:      []
stack:
  - { id: 0, name: x, type: default, offset: 0, size: 4, alignment: 4,
      stack-id: default, callee-saved-register: '', callee-saved-restored: true,
      debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
entry_values:    []
callSites:       []
debugValueSubstitutions: []
constants:       []
machineFunctionInfo: {}
body:             |
  bb.1.entry:
    ; CHECK-LABEL: name: f7
    ; CHECK: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
    ; CHECK-NEXT: [[C1:%[0-9]+]]:_(s32) = G_CONSTANT i32 10
    ; CHECK-NEXT: [[C2:%[0-9]+]]:_(s32) = G_CONSTANT i32 2
    ; CHECK-NEXT: [[C3:%[0-9]+]]:_(s32) = G_CONSTANT i32 3
    ; CHECK-NEXT: [[FRAME_INDEX:%[0-9]+]]:_(p0) = G_FRAME_INDEX %stack.0.x
    ; CHECK-NEXT: G_STORE [[C]](s32), [[FRAME_INDEX]](p0) :: (store (s32) into %ir.x)
    ; CHECK-NEXT: [[LOAD:%[0-9]+]]:_(s32) = G_LOAD [[FRAME_INDEX]](p0) :: (dereferenceable load (s32) from %ir.x)
    ; CHECK-NEXT: ADJCALLSTACKDOWN 0, 0, implicit-def $x2, implicit $x2
    ; CHECK-NEXT: $x10 = COPY [[LOAD]](s32)
    ; CHECK-NEXT: $x11 = COPY [[C1]](s32)
    ; CHECK-NEXT: CALL_PSEUDO &__mulsi3, csr, implicit-def $x1, implicit $x10, implicit $x11, implicit-def $x10
    ; CHECK-NEXT: ADJCALLSTACKUP 0, 0, implicit-def $x2, implicit $x2
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(s32) = COPY $x10
    ; CHECK-NEXT: G_STORE [[COPY]](s32), [[FRAME_INDEX]](p0) :: (store (s32) into %ir.x)
    ; CHECK-NEXT: [[LOAD1:%[0-9]+]]:_(s32) = G_LOAD [[FRAME_INDEX]](p0) :: (dereferenceable load (s32) from %ir.x)
    ; CHECK-NEXT: ADJCALLSTACKDOWN 0, 0, implicit-def $x2, implicit $x2
    ; CHECK-NEXT: $x10 = COPY [[LOAD1]](s32)
    ; CHECK-NEXT: $x11 = COPY [[C2]](s32)
    ; CHECK-NEXT: CALL_PSEUDO &__divsi3, csr, implicit-def $x1, implicit $x10, implicit $x11, implicit-def $x10
    ; CHECK-NEXT: ADJCALLSTACKUP 0, 0, implicit-def $x2, implicit $x2
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY $x10
    ; CHECK-NEXT: G_STORE [[COPY1]](s32), [[FRAME_INDEX]](p0) :: (store (s32) into %ir.x)
    ; CHECK-NEXT: [[LOAD2:%[0-9]+]]:_(s32) = G_LOAD [[FRAME_INDEX]](p0) :: (dereferenceable load (s32) from %ir.x)
    ; CHECK-NEXT: ADJCALLSTACKDOWN 0, 0, implicit-def $x2, implicit $x2
    ; CHECK-NEXT: $x10 = COPY [[LOAD2]](s32)
    ; CHECK-NEXT: $x11 = COPY [[C3]](s32)
    ; CHECK-NEXT: CALL_PSEUDO &__modsi3, csr, implicit-def $x1, implicit $x10, implicit $x11, implicit-def $x10
    ; CHECK-NEXT: ADJCALLSTACKUP 0, 0, implicit-def $x2, implicit $x2
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:_(s32) = COPY $x10
    ; CHECK-NEXT: G_STORE [[COPY2]](s32), [[FRAME_INDEX]](p0) :: (store (s32) into %ir.x)
    ; CHECK-NEXT: [[LOAD3:%[0-9]+]]:_(s32) = G_LOAD [[FRAME_INDEX]](p0) :: (dereferenceable load (s32) from %ir.x)
    ; CHECK-NEXT: [[SUB:%[0-9]+]]:_(s32) = nsw G_SUB [[LOAD3]], [[C2]]
    ; CHECK-NEXT: $x10 = COPY [[SUB]](s32)
    ; CHECK-NEXT: RET_PSEUDO implicit $x10
    %1:_(s32) = G_CONSTANT i32 1
    %3:_(s32) = G_CONSTANT i32 10
    %6:_(s32) = G_CONSTANT i32 2
    %9:_(s32) = G_CONSTANT i32 3
    %0:_(p0) = G_FRAME_INDEX %stack.0.x
    G_STORE %1(s32), %0(p0) :: (store (s32) into %ir.x)
    %2:_(s32) = G_LOAD %0(p0) :: (dereferenceable load (s32) from %ir.x)
    %4:_(s32) = nsw G_MUL %2, %3
    G_STORE %4(s32), %0(p0) :: (store (s32) into %ir.x)
    %5:_(s32) = G_LOAD %0(p0) :: (dereferenceable load (s32) from %ir.x)
    %7:_(s32) = G_SDIV %5, %6
    G_STORE %7(s32), %0(p0) :: (store (s32) into %ir.x)
    %8:_(s32) = G_LOAD %0(p0) :: (dereferenceable load (s32) from %ir.x)
    %10:_(s32) = G_SREM %8, %9
    G_STORE %10(s32), %0(p0) :: (store (s32) into %ir.x)
    %11:_(s32) = G_LOAD %0(p0) :: (dereferenceable load (s32) from %ir.x)
    %12:_(s32) = nsw G_SUB %11, %6
    $x10 = COPY %12(s32)
    RET_PSEUDO implicit $x10
...
---
name:            f8
alignment:       1
exposesReturnsTwice: false
legalized:       false
regBankSelected: false
selected:        false
failedISel:      false
tracksRegLiveness: true
hasWinCFI:       false
noPhis:          false
isSSA:           true
noVRegs:         false
hasFakeUses:     false
callsEHReturn:   false
callsUnwindInit: false
hasEHContTarget: false
hasEHScopes:     false
hasEHFunclets:   false
isOutlined:      false
debugInstrRef:   false
failsVerification: false
tracksDebugUserValues: false
registers:
  - { id: 0, class: _, preferred-register: '', flags: [  ] }
liveins:         []
frameInfo:
  isFrameAddressTaken: false
  isReturnAddressTaken: false
  hasStackMap:     false
  hasPatchPoint:   false
  stackSize:       0
  offsetAdjustment: 0
  maxAlignment:    1
  adjustsStack:    false
  hasCalls:        false
  stackProtector:  ''
  functionContext: ''
  maxCallFrameSize: 4294967295
  cvBytesOfCalleeSavedRegisters: 0
  hasOpaqueSPAdjustment: false
  hasVAStart:      false
  hasMustTailInVarArgFunc: false
  hasTailCall:     false
  isCalleeSavedInfoValid: false
  localFrameSize:  0
fixedStack:      []
stack:           []
entry_values:    []
callSites:       []
debugValueSubstitutions: []
constants:       []
machineFunctionInfo: {}
body:             |
  ; CHECK-LABEL: name: f8
  ; CHECK: bb.0.entry:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1.start:
  ; CHECK-NEXT:   successors: %bb.3(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   G_BR %bb.3
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2.success:
  ; CHECK-NEXT:   $x10 = COPY [[C]](s32)
  ; CHECK-NEXT:   RET_PSEUDO implicit $x10
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.3.next:
  ; CHECK-NEXT:   successors: %bb.4(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.4.foo:
  ; CHECK-NEXT:   successors: %bb.2(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   G_BR %bb.2
  bb.1.entry:
    successors: %bb.2(0x80000000)

    %0:_(s32) = G_CONSTANT i32 0

  bb.2.start:
    successors: %bb.4(0x80000000)

    G_BR %bb.4

  bb.3.success:
    $x10 = COPY %0(s32)
    RET_PSEUDO implicit $x10

  bb.4.next:
    successors: %bb.5(0x80000000)

  bb.5.foo:
    successors: %bb.3(0x80000000)

    G_BR %bb.3
...
---
name:            f9
alignment:       1
exposesReturnsTwice: false
legalized:       false
regBankSelected: false
selected:        false
failedISel:      false
tracksRegLiveness: true
hasWinCFI:       false
noPhis:          false
isSSA:           true
noVRegs:         false
hasFakeUses:     false
callsEHReturn:   false
callsUnwindInit: false
hasEHContTarget: false
hasEHScopes:     false
hasEHFunclets:   false
isOutlined:      false
debugInstrRef:   false
failsVerification: false
tracksDebugUserValues: false
registers:
  - { id: 0, class: _, preferred-register: '', flags: [  ] }
  - { id: 1, class: _, preferred-register: '', flags: [  ] }
  - { id: 2, class: _, preferred-register: '', flags: [  ] }
  - { id: 3, class: _, preferred-register: '', flags: [  ] }
liveins:         []
frameInfo:
  isFrameAddressTaken: false
  isReturnAddressTaken: false
  hasStackMap:     false
  hasPatchPoint:   false
  stackSize:       0
  offsetAdjustment: 0
  maxAlignment:    4
  adjustsStack:    false
  hasCalls:        false
  stackProtector:  ''
  functionContext: ''
  maxCallFrameSize: 4294967295
  cvBytesOfCalleeSavedRegisters: 0
  hasOpaqueSPAdjustment: false
  hasVAStart:      false
  hasMustTailInVarArgFunc: false
  hasTailCall:     false
  isCalleeSavedInfoValid: false
  localFrameSize:  0
fixedStack:      []
stack:
  - { id: 0, name: x, type: default, offset: 0, size: 4, alignment: 4,
      stack-id: default, callee-saved-register: '', callee-saved-restored: true,
      debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  - { id: 1, name: y, type: default, offset: 0, size: 4, alignment: 4,
      stack-id: default, callee-saved-register: '', callee-saved-restored: true,
      debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
entry_values:    []
callSites:       []
debugValueSubstitutions: []
constants:       []
machineFunctionInfo: {}
body:             |
  bb.1.entry:
    ; CHECK-LABEL: name: f9
    ; CHECK: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; CHECK-NEXT: [[FRAME_INDEX:%[0-9]+]]:_(p0) = G_FRAME_INDEX %stack.0.x
    ; CHECK-NEXT: [[FRAME_INDEX1:%[0-9]+]]:_(p0) = G_FRAME_INDEX %stack.1.y
    ; CHECK-NEXT: G_STORE [[C]](s32), [[FRAME_INDEX1]](p0) :: (store (s32) into %ir.y)
    ; CHECK-NEXT: G_STORE [[C]](s32), [[FRAME_INDEX]](p0) :: (store (s32) into %ir.x)
    ; CHECK-NEXT: [[LOAD:%[0-9]+]]:_(s32) = G_LOAD [[FRAME_INDEX]](p0) :: (dereferenceable load (s32) from %ir.x)
    ; CHECK-NEXT: $x10 = COPY [[LOAD]](s32)
    ; CHECK-NEXT: RET_PSEUDO implicit $x10
    %2:_(s32) = G_CONSTANT i32 0
    %0:_(p0) = G_FRAME_INDEX %stack.0.x
    %1:_(p0) = G_FRAME_INDEX %stack.1.y
    G_STORE %2(s32), %1(p0) :: (store (s32) into %ir.y)
    G_STORE %2(s32), %0(p0) :: (store (s32) into %ir.x)
    %3:_(s32) = G_LOAD %0(p0) :: (dereferenceable load (s32) from %ir.x)
    $x10 = COPY %3(s32)
    RET_PSEUDO implicit $x10
...
---
name:            f10
alignment:       1
exposesReturnsTwice: false
legalized:       false
regBankSelected: false
selected:        false
failedISel:      false
tracksRegLiveness: true
hasWinCFI:       false
noPhis:          false
isSSA:           true
noVRegs:         false
hasFakeUses:     false
callsEHReturn:   false
callsUnwindInit: false
hasEHContTarget: false
hasEHScopes:     false
hasEHFunclets:   false
isOutlined:      false
debugInstrRef:   false
failsVerification: false
tracksDebugUserValues: false
registers:
  - { id: 0, class: _, preferred-register: '', flags: [  ] }
liveins:         []
frameInfo:
  isFrameAddressTaken: false
  isReturnAddressTaken: false
  hasStackMap:     false
  hasPatchPoint:   false
  stackSize:       0
  offsetAdjustment: 0
  maxAlignment:    1
  adjustsStack:    false
  hasCalls:        false
  stackProtector:  ''
  functionContext: ''
  maxCallFrameSize: 4294967295
  cvBytesOfCalleeSavedRegisters: 0
  hasOpaqueSPAdjustment: false
  hasVAStart:      false
  hasMustTailInVarArgFunc: false
  hasTailCall:     false
  isCalleeSavedInfoValid: false
  localFrameSize:  0
fixedStack:      []
stack:           []
entry_values:    []
callSites:       []
debugValueSubstitutions: []
constants:       []
machineFunctionInfo: {}
body:             |
  bb.1.entry:
    ; CHECK-LABEL: name: f10
    ; CHECK: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; CHECK-NEXT: $x10 = COPY [[C]](s32)
    ; CHECK-NEXT: RET_PSEUDO implicit $x10
    %0:_(s32) = G_CONSTANT i32 0
    $x10 = COPY %0(s32)
    RET_PSEUDO implicit $x10
...
