# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 5
# How to run: python3 llvm/utils/update_mir_test_checks.py --llc-binary build/bin/llc llvm/test/CodeGen/Giselle/legalizer-addr-op.mir

# RUN: llc -run-pass=legalizer %s -o - -mtriple=giselle -verify-machineinstrs | FileCheck %s
# Check that all the instructions involved in address computation are
# legal.
# Namely this covers:
# - p0 G_PTR_ADD
# - 16|32-bit G_LOAD
# - 16|32-bit G_STORE
# - p0 FRAME_INDEX
# - 16|32-bit G_CONSTANT
---
name: cst16
tracksRegLiveness: true
body:             |
  bb.1:
    liveins: $x1, $x10

    ; CHECK-LABEL: name: cst16
    ; CHECK: liveins: $x1, $x10
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 11
    ; CHECK-NEXT: $x10 = COPY [[C]](s32)
    ; CHECK-NEXT: RET_PSEUDO implicit $x1, implicit $x10
    %0:_(s16) = G_CONSTANT i16 11
    %1:_(s32) = G_ZEXT %0:_(s16)
    $x10 = COPY %1:_(s32)
    RET_PSEUDO implicit $x1, implicit $x10

...

---
name: cst32
tracksRegLiveness: true
body:             |
  bb.1:
    liveins: $x1, $x10

    ; CHECK-LABEL: name: cst32
    ; CHECK: liveins: $x1, $x10
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 132
    ; CHECK-NEXT: $x10 = COPY [[C]](s32)
    ; CHECK-NEXT: RET_PSEUDO implicit $x1, implicit $x10
    %0:_(s32) = G_CONSTANT i32 132
    $x10 = COPY %0(s32)
    RET_PSEUDO implicit $x1, implicit $x10
...
