; NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 6
; How to run: python3 llvm/utils/update_mir_test_checks.py --llc-binary build/bin/llc llvm/test/CodeGen/Giselle/test-suite-translation.ll

; RUN: llc -o - %s -global-isel -global-isel-abort=1 --stop-after=irtranslator -verify-machineinstrs | FileCheck %s

target triple="giselle--"

define dso_local i32 @main() #0 {
  ; CHECK-LABEL: name: main
  ; CHECK: bb.1.entry:
  ; CHECK-NEXT:   [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
  ; CHECK-NEXT:   [[FRAME_INDEX:%[0-9]+]]:_(p0) = G_FRAME_INDEX %stack.0.retval
  ; CHECK-NEXT:   G_STORE [[C]](s32), [[FRAME_INDEX]](p0) :: (store (s32) into %ir.retval)
  ; CHECK-NEXT:   $x10 = COPY [[C]](s32)
  ; CHECK-NEXT:   RET_PSEUDO implicit $x10
entry:
  %retval = alloca i32, align 4
  store i32 0, ptr %retval, align 4
  ret i32 0
}

define dso_local i32 @f0() #0 {
  ; CHECK-LABEL: name: f0
  ; CHECK: bb.1.entry:
  ; CHECK-NEXT:   [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
  ; CHECK-NEXT:   $x10 = COPY [[C]](s32)
  ; CHECK-NEXT:   RET_PSEUDO implicit $x10
entry:
  ret i32 0
}

define dso_local i32 @f1() #0 {
  ; CHECK-LABEL: name: f1
  ; CHECK: bb.1.entry:
  ; CHECK-NEXT:   [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 4
  ; CHECK-NEXT:   [[FRAME_INDEX:%[0-9]+]]:_(p0) = G_FRAME_INDEX %stack.0.x
  ; CHECK-NEXT:   G_STORE [[C]](s32), [[FRAME_INDEX]](p0) :: (store (s32) into %ir.x)
  ; CHECK-NEXT:   [[LOAD:%[0-9]+]]:_(s32) = G_LOAD [[FRAME_INDEX]](p0) :: (dereferenceable load (s32) from %ir.x)
  ; CHECK-NEXT:   [[SUB:%[0-9]+]]:_(s32) = nsw G_SUB [[LOAD]], [[C]]
  ; CHECK-NEXT:   $x10 = COPY [[SUB]](s32)
  ; CHECK-NEXT:   RET_PSEUDO implicit $x10
entry:
  %x = alloca i32, align 4
  store i32 4, ptr %x, align 4
  %0 = load i32, ptr %x, align 4
  %sub = sub nsw i32 %0, 4
  ret i32 %sub
}

define dso_local i32 @f2() #0 {
  ; CHECK-LABEL: name: f2
  ; CHECK: bb.1.entry:
  ; CHECK-NEXT:   [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 4
  ; CHECK-NEXT:   [[C1:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
  ; CHECK-NEXT:   [[FRAME_INDEX:%[0-9]+]]:_(p0) = G_FRAME_INDEX %stack.0.x
  ; CHECK-NEXT:   [[FRAME_INDEX1:%[0-9]+]]:_(p0) = G_FRAME_INDEX %stack.1.p
  ; CHECK-NEXT:   G_STORE [[C]](s32), [[FRAME_INDEX]](p0) :: (store (s32) into %ir.x)
  ; CHECK-NEXT:   G_STORE [[FRAME_INDEX]](p0), [[FRAME_INDEX1]](p0) :: (store (p0) into %ir.p)
  ; CHECK-NEXT:   [[LOAD:%[0-9]+]]:_(p0) = G_LOAD [[FRAME_INDEX1]](p0) :: (dereferenceable load (p0) from %ir.p)
  ; CHECK-NEXT:   G_STORE [[C1]](s32), [[LOAD]](p0) :: (store (s32) into %ir.0)
  ; CHECK-NEXT:   [[LOAD1:%[0-9]+]]:_(p0) = G_LOAD [[FRAME_INDEX1]](p0) :: (dereferenceable load (p0) from %ir.p)
  ; CHECK-NEXT:   [[LOAD2:%[0-9]+]]:_(s32) = G_LOAD [[LOAD1]](p0) :: (load (s32) from %ir.1)
  ; CHECK-NEXT:   $x10 = COPY [[LOAD2]](s32)
  ; CHECK-NEXT:   RET_PSEUDO implicit $x10
entry:
  %x = alloca i32, align 4
  %p = alloca ptr, align 4
  store i32 4, ptr %x, align 4
  store ptr %x, ptr %p, align 4
  %0 = load ptr, ptr %p, align 4
  store i32 0, ptr %0, align 4
  %1 = load ptr, ptr %p, align 4
  %2 = load i32, ptr %1, align 4
  ret i32 %2
}

define dso_local i32 @f3() #0 {
  ; CHECK-LABEL: name: f3
  ; CHECK: bb.1.entry:
  ; CHECK-NEXT:   successors: %bb.2(0x40000000), %bb.3(0x40000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
  ; CHECK-NEXT:   [[C1:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
  ; CHECK-NEXT:   [[FRAME_INDEX:%[0-9]+]]:_(p0) = G_FRAME_INDEX %stack.0.retval
  ; CHECK-NEXT:   [[FRAME_INDEX1:%[0-9]+]]:_(p0) = G_FRAME_INDEX %stack.1.x
  ; CHECK-NEXT:   [[FRAME_INDEX2:%[0-9]+]]:_(p0) = G_FRAME_INDEX %stack.2.p
  ; CHECK-NEXT:   [[FRAME_INDEX3:%[0-9]+]]:_(p0) = G_FRAME_INDEX %stack.3.pp
  ; CHECK-NEXT:   G_STORE [[C]](s32), [[FRAME_INDEX1]](p0) :: (store (s32) into %ir.x)
  ; CHECK-NEXT:   G_STORE [[FRAME_INDEX1]](p0), [[FRAME_INDEX2]](p0) :: (store (p0) into %ir.p)
  ; CHECK-NEXT:   G_STORE [[FRAME_INDEX2]](p0), [[FRAME_INDEX3]](p0) :: (store (p0) into %ir.pp)
  ; CHECK-NEXT:   [[LOAD:%[0-9]+]]:_(p0) = G_LOAD [[FRAME_INDEX2]](p0) :: (dereferenceable load (p0) from %ir.p)
  ; CHECK-NEXT:   [[LOAD1:%[0-9]+]]:_(s32) = G_LOAD [[LOAD]](p0) :: (load (s32) from %ir.0)
  ; CHECK-NEXT:   [[ICMP:%[0-9]+]]:_(s1) = G_ICMP intpred(ne), [[LOAD1]](s32), [[C]]
  ; CHECK-NEXT:   G_BRCOND [[ICMP]](s1), %bb.2
  ; CHECK-NEXT:   G_BR %bb.3
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2.if.then:
  ; CHECK-NEXT:   successors: %bb.9(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   G_STORE [[C1]](s32), [[FRAME_INDEX]](p0) :: (store (s32) into %ir.retval)
  ; CHECK-NEXT:   G_BR %bb.9
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.3.if.end:
  ; CHECK-NEXT:   successors: %bb.4(0x40000000), %bb.5(0x40000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[LOAD2:%[0-9]+]]:_(p0) = G_LOAD [[FRAME_INDEX3]](p0) :: (dereferenceable load (p0) from %ir.pp)
  ; CHECK-NEXT:   [[LOAD3:%[0-9]+]]:_(p0) = G_LOAD [[LOAD2]](p0) :: (load (p0) from %ir.2)
  ; CHECK-NEXT:   [[LOAD4:%[0-9]+]]:_(s32) = G_LOAD [[LOAD3]](p0) :: (load (s32) from %ir.3)
  ; CHECK-NEXT:   [[ICMP1:%[0-9]+]]:_(s1) = G_ICMP intpred(ne), [[LOAD4]](s32), [[C]]
  ; CHECK-NEXT:   G_BRCOND [[ICMP1]](s1), %bb.4
  ; CHECK-NEXT:   G_BR %bb.5
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.4.if.then2:
  ; CHECK-NEXT:   successors: %bb.9(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   G_STORE [[C1]](s32), [[FRAME_INDEX]](p0) :: (store (s32) into %ir.retval)
  ; CHECK-NEXT:   G_BR %bb.9
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.5.if.else:
  ; CHECK-NEXT:   successors: %bb.6(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[LOAD5:%[0-9]+]]:_(p0) = G_LOAD [[FRAME_INDEX3]](p0) :: (dereferenceable load (p0) from %ir.pp)
  ; CHECK-NEXT:   [[LOAD6:%[0-9]+]]:_(p0) = G_LOAD [[LOAD5]](p0) :: (load (p0) from %ir.5)
  ; CHECK-NEXT:   G_STORE [[C1]](s32), [[LOAD6]](p0) :: (store (s32) into %ir.6)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.6.if.end3:
  ; CHECK-NEXT:   successors: %bb.7(0x40000000), %bb.8(0x40000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[LOAD7:%[0-9]+]]:_(s32) = G_LOAD [[FRAME_INDEX1]](p0) :: (dereferenceable load (s32) from %ir.x)
  ; CHECK-NEXT:   [[ICMP2:%[0-9]+]]:_(s1) = G_ICMP intpred(ne), [[LOAD7]](s32), [[C]]
  ; CHECK-NEXT:   G_BRCOND [[ICMP2]](s1), %bb.7
  ; CHECK-NEXT:   G_BR %bb.8
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.7.if.then5:
  ; CHECK-NEXT:   successors: %bb.9(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   G_STORE [[C]](s32), [[FRAME_INDEX]](p0) :: (store (s32) into %ir.retval)
  ; CHECK-NEXT:   G_BR %bb.9
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.8.if.else6:
  ; CHECK-NEXT:   successors: %bb.9(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   G_STORE [[C1]](s32), [[FRAME_INDEX]](p0) :: (store (s32) into %ir.retval)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.9.return:
  ; CHECK-NEXT:   [[LOAD8:%[0-9]+]]:_(s32) = G_LOAD [[FRAME_INDEX]](p0) :: (dereferenceable load (s32) from %ir.retval)
  ; CHECK-NEXT:   $x10 = COPY [[LOAD8]](s32)
  ; CHECK-NEXT:   RET_PSEUDO implicit $x10
entry:
  %retval = alloca i32, align 4
  %x = alloca i32, align 4
  %p = alloca ptr, align 4
  %pp = alloca ptr, align 4
  store i32 0, ptr %x, align 4
  store ptr %x, ptr %p, align 4
  store ptr %p, ptr %pp, align 4
  %0 = load ptr, ptr %p, align 4
  %1 = load i32, ptr %0, align 4
  %tobool = icmp ne i32 %1, 0
  br i1 %tobool, label %if.then, label %if.end

if.then:                                          ; preds = %entry
  store i32 1, ptr %retval, align 4
  br label %return

if.end:                                           ; preds = %entry
  %2 = load ptr, ptr %pp, align 4
  %3 = load ptr, ptr %2, align 4
  %4 = load i32, ptr %3, align 4
  %tobool1 = icmp ne i32 %4, 0
  br i1 %tobool1, label %if.then2, label %if.else

if.then2:                                         ; preds = %if.end
  store i32 1, ptr %retval, align 4
  br label %return

if.else:                                          ; preds = %if.end
  %5 = load ptr, ptr %pp, align 4
  %6 = load ptr, ptr %5, align 4
  store i32 1, ptr %6, align 4
  br label %if.end3

if.end3:                                          ; preds = %if.else
  %7 = load i32, ptr %x, align 4
  %tobool4 = icmp ne i32 %7, 0
  br i1 %tobool4, label %if.then5, label %if.else6

if.then5:                                         ; preds = %if.end3
  store i32 0, ptr %retval, align 4
  br label %return

if.else6:                                         ; preds = %if.end3
  store i32 1, ptr %retval, align 4
  br label %return

return:                                           ; preds = %if.else6, %if.then5, %if.then2, %if.then
  %8 = load i32, ptr %retval, align 4
  ret i32 %8
}

define dso_local i32 @f4() #0 {
  ; CHECK-LABEL: name: f4
  ; CHECK: bb.1.entry:
  ; CHECK-NEXT:   successors: %bb.2(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 50
  ; CHECK-NEXT:   [[C1:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
  ; CHECK-NEXT:   [[C2:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
  ; CHECK-NEXT:   [[FRAME_INDEX:%[0-9]+]]:_(p0) = G_FRAME_INDEX %stack.0.x
  ; CHECK-NEXT:   G_STORE [[C]](s32), [[FRAME_INDEX]](p0) :: (store (s32) into %ir.x)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2.while.cond:
  ; CHECK-NEXT:   successors: %bb.3(0x40000000), %bb.4(0x40000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[LOAD:%[0-9]+]]:_(s32) = G_LOAD [[FRAME_INDEX]](p0) :: (dereferenceable load (s32) from %ir.x)
  ; CHECK-NEXT:   [[ICMP:%[0-9]+]]:_(s1) = G_ICMP intpred(ne), [[LOAD]](s32), [[C1]]
  ; CHECK-NEXT:   G_BRCOND [[ICMP]](s1), %bb.3
  ; CHECK-NEXT:   G_BR %bb.4
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.3.while.body:
  ; CHECK-NEXT:   successors: %bb.2(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[LOAD1:%[0-9]+]]:_(s32) = G_LOAD [[FRAME_INDEX]](p0) :: (dereferenceable load (s32) from %ir.x)
  ; CHECK-NEXT:   [[SUB:%[0-9]+]]:_(s32) = nsw G_SUB [[LOAD1]], [[C2]]
  ; CHECK-NEXT:   G_STORE [[SUB]](s32), [[FRAME_INDEX]](p0) :: (store (s32) into %ir.x)
  ; CHECK-NEXT:   G_BR %bb.2
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.4.while.end:
  ; CHECK-NEXT:   [[LOAD2:%[0-9]+]]:_(s32) = G_LOAD [[FRAME_INDEX]](p0) :: (dereferenceable load (s32) from %ir.x)
  ; CHECK-NEXT:   $x10 = COPY [[LOAD2]](s32)
  ; CHECK-NEXT:   RET_PSEUDO implicit $x10
entry:
  %x = alloca i32, align 4
  store i32 50, ptr %x, align 4
  br label %while.cond

while.cond:                                       ; preds = %while.body, %entry
  %0 = load i32, ptr %x, align 4
  %tobool = icmp ne i32 %0, 0
  br i1 %tobool, label %while.body, label %while.end

while.body:                                       ; preds = %while.cond
  %1 = load i32, ptr %x, align 4
  %sub = sub nsw i32 %1, 1
  store i32 %sub, ptr %x, align 4
  br label %while.cond, !llvm.loop !2

while.end:                                        ; preds = %while.cond
  %2 = load i32, ptr %x, align 4
  ret i32 %2
}

define dso_local i32 @f5() #0 {
  ; CHECK-LABEL: name: f5
  ; CHECK: bb.1.entry:
  ; CHECK-NEXT:   successors: %bb.2(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
  ; CHECK-NEXT:   [[C1:%[0-9]+]]:_(s32) = G_CONSTANT i32 10
  ; CHECK-NEXT:   [[C2:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
  ; CHECK-NEXT:   [[FRAME_INDEX:%[0-9]+]]:_(p0) = G_FRAME_INDEX %stack.0.retval
  ; CHECK-NEXT:   [[FRAME_INDEX1:%[0-9]+]]:_(p0) = G_FRAME_INDEX %stack.1.x
  ; CHECK-NEXT:   G_STORE [[C]](s32), [[FRAME_INDEX1]](p0) :: (store (s32) into %ir.x)
  ; CHECK-NEXT:   G_STORE [[C1]](s32), [[FRAME_INDEX1]](p0) :: (store (s32) into %ir.x)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2.for.cond:
  ; CHECK-NEXT:   successors: %bb.3(0x40000000), %bb.5(0x40000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[LOAD:%[0-9]+]]:_(s32) = G_LOAD [[FRAME_INDEX1]](p0) :: (dereferenceable load (s32) from %ir.x)
  ; CHECK-NEXT:   [[ICMP:%[0-9]+]]:_(s1) = G_ICMP intpred(ne), [[LOAD]](s32), [[C2]]
  ; CHECK-NEXT:   G_BRCOND [[ICMP]](s1), %bb.3
  ; CHECK-NEXT:   G_BR %bb.5
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.3.for.body:
  ; CHECK-NEXT:   successors: %bb.4(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.4.for.inc:
  ; CHECK-NEXT:   successors: %bb.2(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[LOAD1:%[0-9]+]]:_(s32) = G_LOAD [[FRAME_INDEX1]](p0) :: (dereferenceable load (s32) from %ir.x)
  ; CHECK-NEXT:   [[SUB:%[0-9]+]]:_(s32) = nsw G_SUB [[LOAD1]], [[C]]
  ; CHECK-NEXT:   G_STORE [[SUB]](s32), [[FRAME_INDEX1]](p0) :: (store (s32) into %ir.x)
  ; CHECK-NEXT:   G_BR %bb.2
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.5.for.end:
  ; CHECK-NEXT:   successors: %bb.6(0x40000000), %bb.7(0x40000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[LOAD2:%[0-9]+]]:_(s32) = G_LOAD [[FRAME_INDEX1]](p0) :: (dereferenceable load (s32) from %ir.x)
  ; CHECK-NEXT:   [[ICMP1:%[0-9]+]]:_(s1) = G_ICMP intpred(ne), [[LOAD2]](s32), [[C2]]
  ; CHECK-NEXT:   G_BRCOND [[ICMP1]](s1), %bb.6
  ; CHECK-NEXT:   G_BR %bb.7
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.6.if.then:
  ; CHECK-NEXT:   successors: %bb.11(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   G_STORE [[C]](s32), [[FRAME_INDEX]](p0) :: (store (s32) into %ir.retval)
  ; CHECK-NEXT:   G_BR %bb.11
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.7.if.end:
  ; CHECK-NEXT:   successors: %bb.8(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   G_STORE [[C1]](s32), [[FRAME_INDEX1]](p0) :: (store (s32) into %ir.x)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.8.for.cond2:
  ; CHECK-NEXT:   successors: %bb.9(0x40000000), %bb.10(0x40000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[LOAD3:%[0-9]+]]:_(s32) = G_LOAD [[FRAME_INDEX1]](p0) :: (dereferenceable load (s32) from %ir.x)
  ; CHECK-NEXT:   [[ICMP2:%[0-9]+]]:_(s1) = G_ICMP intpred(ne), [[LOAD3]](s32), [[C2]]
  ; CHECK-NEXT:   G_BRCOND [[ICMP2]](s1), %bb.9
  ; CHECK-NEXT:   G_BR %bb.10
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.9.for.body4:
  ; CHECK-NEXT:   successors: %bb.8(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[LOAD4:%[0-9]+]]:_(s32) = G_LOAD [[FRAME_INDEX1]](p0) :: (dereferenceable load (s32) from %ir.x)
  ; CHECK-NEXT:   [[SUB1:%[0-9]+]]:_(s32) = nsw G_SUB [[LOAD4]], [[C]]
  ; CHECK-NEXT:   G_STORE [[SUB1]](s32), [[FRAME_INDEX1]](p0) :: (store (s32) into %ir.x)
  ; CHECK-NEXT:   G_BR %bb.8
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.10.for.end6:
  ; CHECK-NEXT:   successors: %bb.11(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[LOAD5:%[0-9]+]]:_(s32) = G_LOAD [[FRAME_INDEX1]](p0) :: (dereferenceable load (s32) from %ir.x)
  ; CHECK-NEXT:   G_STORE [[LOAD5]](s32), [[FRAME_INDEX]](p0) :: (store (s32) into %ir.retval)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.11.return:
  ; CHECK-NEXT:   [[LOAD6:%[0-9]+]]:_(s32) = G_LOAD [[FRAME_INDEX]](p0) :: (dereferenceable load (s32) from %ir.retval)
  ; CHECK-NEXT:   $x10 = COPY [[LOAD6]](s32)
  ; CHECK-NEXT:   RET_PSEUDO implicit $x10
entry:
  %retval = alloca i32, align 4
  %x = alloca i32, align 4
  store i32 1, ptr %x, align 4
  store i32 10, ptr %x, align 4
  br label %for.cond

for.cond:                                         ; preds = %for.inc, %entry
  %0 = load i32, ptr %x, align 4
  %tobool = icmp ne i32 %0, 0
  br i1 %tobool, label %for.body, label %for.end

for.body:                                         ; preds = %for.cond
  br label %for.inc

for.inc:                                          ; preds = %for.body
  %1 = load i32, ptr %x, align 4
  %sub = sub nsw i32 %1, 1
  store i32 %sub, ptr %x, align 4
  br label %for.cond, !llvm.loop !4

for.end:                                          ; preds = %for.cond
  %2 = load i32, ptr %x, align 4
  %tobool1 = icmp ne i32 %2, 0
  br i1 %tobool1, label %if.then, label %if.end

if.then:                                          ; preds = %for.end
  store i32 1, ptr %retval, align 4
  br label %return

if.end:                                           ; preds = %for.end
  store i32 10, ptr %x, align 4
  br label %for.cond2

for.cond2:                                        ; preds = %for.body4, %if.end
  %3 = load i32, ptr %x, align 4
  %tobool3 = icmp ne i32 %3, 0
  br i1 %tobool3, label %for.body4, label %for.end6

for.body4:                                        ; preds = %for.cond2
  %4 = load i32, ptr %x, align 4
  %sub5 = sub nsw i32 %4, 1
  store i32 %sub5, ptr %x, align 4
  br label %for.cond2, !llvm.loop !5

for.end6:                                         ; preds = %for.cond2
  %5 = load i32, ptr %x, align 4
  store i32 %5, ptr %retval, align 4
  br label %return

return:                                           ; preds = %for.end6, %if.then
  %6 = load i32, ptr %retval, align 4
  ret i32 %6
}

define dso_local i32 @f6() #0 {
  ; CHECK-LABEL: name: f6
  ; CHECK: bb.1.entry:
  ; CHECK-NEXT:   successors: %bb.2(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 50
  ; CHECK-NEXT:   [[C1:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
  ; CHECK-NEXT:   [[C2:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
  ; CHECK-NEXT:   [[FRAME_INDEX:%[0-9]+]]:_(p0) = G_FRAME_INDEX %stack.0.x
  ; CHECK-NEXT:   G_STORE [[C]](s32), [[FRAME_INDEX]](p0) :: (store (s32) into %ir.x)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2.do.body:
  ; CHECK-NEXT:   successors: %bb.3(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[LOAD:%[0-9]+]]:_(s32) = G_LOAD [[FRAME_INDEX]](p0) :: (dereferenceable load (s32) from %ir.x)
  ; CHECK-NEXT:   [[SUB:%[0-9]+]]:_(s32) = nsw G_SUB [[LOAD]], [[C1]]
  ; CHECK-NEXT:   G_STORE [[SUB]](s32), [[FRAME_INDEX]](p0) :: (store (s32) into %ir.x)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.3.do.cond:
  ; CHECK-NEXT:   successors: %bb.2(0x40000000), %bb.4(0x40000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[LOAD1:%[0-9]+]]:_(s32) = G_LOAD [[FRAME_INDEX]](p0) :: (dereferenceable load (s32) from %ir.x)
  ; CHECK-NEXT:   [[ICMP:%[0-9]+]]:_(s1) = G_ICMP intpred(ne), [[LOAD1]](s32), [[C2]]
  ; CHECK-NEXT:   G_BRCOND [[ICMP]](s1), %bb.2
  ; CHECK-NEXT:   G_BR %bb.4
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.4.do.end:
  ; CHECK-NEXT:   [[LOAD2:%[0-9]+]]:_(s32) = G_LOAD [[FRAME_INDEX]](p0) :: (dereferenceable load (s32) from %ir.x)
  ; CHECK-NEXT:   $x10 = COPY [[LOAD2]](s32)
  ; CHECK-NEXT:   RET_PSEUDO implicit $x10
entry:
  %x = alloca i32, align 4
  store i32 50, ptr %x, align 4
  br label %do.body

do.body:                                          ; preds = %do.cond, %entry
  %0 = load i32, ptr %x, align 4
  %sub = sub nsw i32 %0, 1
  store i32 %sub, ptr %x, align 4
  br label %do.cond

do.cond:                                          ; preds = %do.body
  %1 = load i32, ptr %x, align 4
  %tobool = icmp ne i32 %1, 0
  br i1 %tobool, label %do.body, label %do.end, !llvm.loop !6

do.end:                                           ; preds = %do.cond
  %2 = load i32, ptr %x, align 4
  ret i32 %2
}

define dso_local i32 @f7() #0 {
  ; CHECK-LABEL: name: f7
  ; CHECK: bb.1.entry:
  ; CHECK-NEXT:   [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
  ; CHECK-NEXT:   [[C1:%[0-9]+]]:_(s32) = G_CONSTANT i32 10
  ; CHECK-NEXT:   [[C2:%[0-9]+]]:_(s32) = G_CONSTANT i32 2
  ; CHECK-NEXT:   [[C3:%[0-9]+]]:_(s32) = G_CONSTANT i32 3
  ; CHECK-NEXT:   [[FRAME_INDEX:%[0-9]+]]:_(p0) = G_FRAME_INDEX %stack.0.x
  ; CHECK-NEXT:   G_STORE [[C]](s32), [[FRAME_INDEX]](p0) :: (store (s32) into %ir.x)
  ; CHECK-NEXT:   [[LOAD:%[0-9]+]]:_(s32) = G_LOAD [[FRAME_INDEX]](p0) :: (dereferenceable load (s32) from %ir.x)
  ; CHECK-NEXT:   [[MUL:%[0-9]+]]:_(s32) = nsw G_MUL [[LOAD]], [[C1]]
  ; CHECK-NEXT:   G_STORE [[MUL]](s32), [[FRAME_INDEX]](p0) :: (store (s32) into %ir.x)
  ; CHECK-NEXT:   [[LOAD1:%[0-9]+]]:_(s32) = G_LOAD [[FRAME_INDEX]](p0) :: (dereferenceable load (s32) from %ir.x)
  ; CHECK-NEXT:   [[SDIV:%[0-9]+]]:_(s32) = G_SDIV [[LOAD1]], [[C2]]
  ; CHECK-NEXT:   G_STORE [[SDIV]](s32), [[FRAME_INDEX]](p0) :: (store (s32) into %ir.x)
  ; CHECK-NEXT:   [[LOAD2:%[0-9]+]]:_(s32) = G_LOAD [[FRAME_INDEX]](p0) :: (dereferenceable load (s32) from %ir.x)
  ; CHECK-NEXT:   [[SREM:%[0-9]+]]:_(s32) = G_SREM [[LOAD2]], [[C3]]
  ; CHECK-NEXT:   G_STORE [[SREM]](s32), [[FRAME_INDEX]](p0) :: (store (s32) into %ir.x)
  ; CHECK-NEXT:   [[LOAD3:%[0-9]+]]:_(s32) = G_LOAD [[FRAME_INDEX]](p0) :: (dereferenceable load (s32) from %ir.x)
  ; CHECK-NEXT:   [[SUB:%[0-9]+]]:_(s32) = nsw G_SUB [[LOAD3]], [[C2]]
  ; CHECK-NEXT:   $x10 = COPY [[SUB]](s32)
  ; CHECK-NEXT:   RET_PSEUDO implicit $x10
entry:
  %x = alloca i32, align 4
  store i32 1, ptr %x, align 4
  %0 = load i32, ptr %x, align 4
  %mul = mul nsw i32 %0, 10
  store i32 %mul, ptr %x, align 4
  %1 = load i32, ptr %x, align 4
  %div = sdiv i32 %1, 2
  store i32 %div, ptr %x, align 4
  %2 = load i32, ptr %x, align 4
  %rem = srem i32 %2, 3
  store i32 %rem, ptr %x, align 4
  %3 = load i32, ptr %x, align 4
  %sub = sub nsw i32 %3, 2
  ret i32 %sub
}

define dso_local i32 @f8() #0 {
  ; CHECK-LABEL: name: f8
  ; CHECK: bb.1.entry:
  ; CHECK-NEXT:   successors: %bb.2(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2.start:
  ; CHECK-NEXT:   successors: %bb.4(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   G_BR %bb.4
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.3.success:
  ; CHECK-NEXT:   $x10 = COPY [[C]](s32)
  ; CHECK-NEXT:   RET_PSEUDO implicit $x10
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.4.next:
  ; CHECK-NEXT:   successors: %bb.5(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.5.foo:
  ; CHECK-NEXT:   successors: %bb.3(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   G_BR %bb.3
entry:
  br label %start

start:                                            ; preds = %entry
  br label %next

success:                                          ; preds = %foo
  ret i32 0

next:                                             ; preds = %start
  br label %foo

foo:                                              ; preds = %next
  br label %success
}

define dso_local i32 @f9() #0 {
  ; CHECK-LABEL: name: f9
  ; CHECK: bb.1.entry:
  ; CHECK-NEXT:   [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
  ; CHECK-NEXT:   [[FRAME_INDEX:%[0-9]+]]:_(p0) = G_FRAME_INDEX %stack.0.x
  ; CHECK-NEXT:   [[FRAME_INDEX1:%[0-9]+]]:_(p0) = G_FRAME_INDEX %stack.1.y
  ; CHECK-NEXT:   G_STORE [[C]](s32), [[FRAME_INDEX1]](p0) :: (store (s32) into %ir.y)
  ; CHECK-NEXT:   G_STORE [[C]](s32), [[FRAME_INDEX]](p0) :: (store (s32) into %ir.x)
  ; CHECK-NEXT:   [[LOAD:%[0-9]+]]:_(s32) = G_LOAD [[FRAME_INDEX]](p0) :: (dereferenceable load (s32) from %ir.x)
  ; CHECK-NEXT:   $x10 = COPY [[LOAD]](s32)
  ; CHECK-NEXT:   RET_PSEUDO implicit $x10
entry:
  %x = alloca i32, align 4
  %y = alloca i32, align 4
  store i32 0, ptr %y, align 4
  store i32 0, ptr %x, align 4
  %0 = load i32, ptr %x, align 4
  ret i32 %0
}

define dso_local i32 @f10() #0 {
  ; CHECK-LABEL: name: f10
  ; CHECK: bb.1.entry:
  ; CHECK-NEXT:   [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
  ; CHECK-NEXT:   $x10 = COPY [[C]](s32)
  ; CHECK-NEXT:   RET_PSEUDO implicit $x10
entry:
  ret i32 0
}

attributes #0 = { noinline nounwind optnone "no-trapping-math"="true" "stack-protector-buffer-size"="8" }

!llvm.module.flags = !{!0}
!llvm.ident = !{!1}

!0 = !{i32 1, !"wchar_size", i32 4}
!1 = !{!"clang version 22.1.0 (git@github.com:ZakyHermawan/Giselle.git 1208af47eafc4f092a20f130dd37e209ce8438a5)"}
!2 = distinct !{!2, !3}
!3 = !{!"llvm.loop.mustprogress"}
!4 = distinct !{!4, !3}
!5 = distinct !{!5, !3}
!6 = distinct !{!6, !3}
